ALTER TABLE "Run" ADD COLUMN "classRewardChoices" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Run" ADD COLUMN "relicChoices" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Run" ADD COLUMN "relics" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "GhostSnapshot" ADD COLUMN "relics" TEXT NOT NULL DEFAULT '[]';
