import { existsSync, readFileSync, statSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const css = readFileSync(new URL('./App.css', import.meta.url), 'utf8')
const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const primitives = readFileSync(new URL('./ui/primitives.tsx', import.meta.url), 'utf8')
const uiCss = existsSync(new URL('./ui/handdrawn.css', import.meta.url))
  ? readFileSync(new URL('./ui/handdrawn.css', import.meta.url), 'utf8')
  : ''
const dogBrawlTownBackgroundUrl = new URL('../public/assets/backgrounds/dog-brawl-town.jpg', import.meta.url)

function cssVariablePx(name: string) {
  const match = css.match(new RegExp(`${name}:\\s*(\\d+)px`))
  return match ? Number(match[1]) : null
}

function cssRule(selector: string) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = css.match(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`, 's'))
  return match?.[1] ?? ''
}

function lastCssRule(selector: string) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const matches = [...css.matchAll(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`, 'gs'))]
  return matches.at(-1)?.[1] ?? ''
}

function uiCssRule(selector: string) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = uiCss.match(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`, 's'))
  return match?.[1] ?? ''
}

function cssVariableValue(name: string) {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = css.match(new RegExp(`${escaped}:\\s*([\\s\\S]*?);\\s*--`, 's'))
  return match?.[1] ?? ''
}

describe('equipment layout scale', () => {
  it('defines reusable handdrawn UI tokens and ornamental frame variants', () => {
    expect(uiCss).toContain('--handdrawn-frame-border')
    expect(uiCss).toContain('--handdrawn-inner-line')
    expect(uiCss).toContain('--handdrawn-corner-ornament')
    expect(uiCssRule('.handdrawn-frame')).toContain('border: var(--handdrawn-frame-border) solid')
    expect(uiCssRule('.handdrawn-frame::before')).toContain('var(--handdrawn-corner-ornament)')
    expect(uiCssRule('.handdrawn-frame-wood')).toContain('var(--wood-frame)')
    expect(uiCssRule('.handdrawn-button:active, .handdrawn-button.pressed')).toContain('translateY')
    expect(uiCssRule('.floating-paper-tip')).toContain('border')
    expect(uiCssRule('.handdrawn-status-chip')).toContain('border')
    expect(uiCssRule('.handdrawn-choice-card')).toContain('position: relative')
    expect(uiCssRule('.handdrawn-item-frame')).toContain('position: relative')
    expect(uiCssRule('.handdrawn-item-frame:where(button)')).toContain('cursor: pointer')
    expect(uiCssRule('.handdrawn-text-button')).toContain('cursor: pointer')
    expect(uiCssRule('.handdrawn-tab-button.active, .handdrawn-list-button.selected, .handdrawn-number-button.selected')).toContain('translateY')
    expect(uiCssRule('.handdrawn-slot-button')).toContain('cursor: pointer')
    expect(uiCssRule('.handdrawn-relic-icon-button')).toContain('border-radius: 999px')
  })

  it('styles global dog avatars as circular handdrawn badges', () => {
    expect(uiCssRule('.dog-badge')).toContain('border-radius: 999px')
    expect(uiCssRule('.dog-badge')).toContain('border')
    expect(uiCssRule('.dog-badge::before')).toContain('radial-gradient')
    expect(uiCssRule('.dog-badge img')).toContain('border-radius: 999px')
    expect(css).toContain('.dog-avatar')
  })

  it('styles battle health as a bone framed bar with shield and poison layers', () => {
    expect(uiCssRule('.bone-health .bone-health-bar')).toContain('height: 44px')
    expect(uiCssRule('.bone-health .bone-health-bar')).toContain('overflow: hidden')
    expect(uiCssRule('.bone-health .bone-health-track')).toContain('fill: var(--handdrawn-bone-paper)')
    expect(uiCssRule('.bone-health .bone-health-outline')).toContain('stroke: var(--handdrawn-bone-edge)')
    expect(uiCssRule('.bone-health .bone-health-fill')).toContain('transition: width')
    expect(uiCssRule('.bone-health .bone-health-shield')).toContain('fill')
    expect(uiCssRule('.bone-health .bone-health-poison')).toContain('fill')
  })

  it('keeps legacy hp descendant rules from overriding the bone health bar shape', () => {
    expect(css).not.toContain('.hp div {')
    expect(css).not.toContain('.hp i {')
    expect(css).not.toContain('.hp .hp-bar {')
    expect(css).not.toContain('.hp .hp-bar i {')
    expect(uiCssRule('.bone-health .bone-health-bar')).toContain('overflow: hidden')
    expect(uiCssRule('.bone-health .bone-health-fill')).toContain('fill: #ec5f6d')
  })

  it('renders battle health as one clipped bone shape instead of separate endpoint pieces', () => {
    expect(primitives).toContain('<svg className="bone-health-svg"')
    expect(primitives).toContain('<clipPath id={clipId}>')
    expect(primitives).toContain('className="bone-health-track"')
    expect(primitives).toContain('className="bone-health-outline"')
    expect(primitives).not.toContain('bone-health-knob')
    expect(uiCssRule('.bone-health .bone-health-bar')).toContain('overflow: hidden')
    expect(uiCssRule('.bone-health .bone-health-svg')).toContain('display: block')
    expect(uiCssRule('.bone-health .bone-health-track')).toContain('fill: var(--handdrawn-bone-paper)')
    expect(uiCssRule('.bone-health .bone-health-outline')).toContain('stroke: var(--handdrawn-bone-edge)')
    expect(primitives).toContain('className="bone-health-fill hp-current"')
    expect(primitives).toContain('className="bone-health-shield hp-shield"')
    expect(primitives).toContain('className="bone-health-poison hp-preview poison"')
    expect(primitives).toContain('clipPath={`url(#${clipId})`}')
  })

  it('styles the center dice as a readable front-facing handdrawn die', () => {
    expect(uiCssRule('.dynamic-dice')).toContain('--dice-size')
    expect(uiCssRule('.dynamic-dice')).not.toContain('perspective')
    expect(uiCssRule('.dynamic-dice-cube')).toContain('width: var(--dice-size)')
    expect(uiCssRule('.dynamic-dice-cube')).not.toContain('transform-style: preserve-3d')
    expect(uiCssRule('.dynamic-dice-face.front')).toContain('position: relative')
    expect(uiCssRule('.dynamic-dice-face.top, .dynamic-dice-face.side')).toContain('display: none')
    expect(uiCssRule('.dynamic-dice-value')).toContain('display: none')
    expect(uiCssRule('.dynamic-dice-pips i.active')).toContain('transform: scale')
    expect(uiCssRule('.dynamic-dice.rolling .dynamic-dice-cube')).toContain('animation')
    expect(uiCss).toContain('@keyframes handdrawnDiceRoll')
  })

  it('keeps equipment and bag slots large enough to be the core play surface', () => {
    expect(cssVariablePx('--slot-w')).toBeGreaterThanOrEqual(84)
    expect(cssVariablePx('--slot-h')).toBeGreaterThanOrEqual(102)
    expect(cssVariablePx('--board-slot-h')).toBeGreaterThanOrEqual(220)
    expect(app).toContain('inventory-board expanded')
    expect(css).toContain('overflow-x: visible')
    expect(app).toContain('repeat(${w}, minmax(0, 1fr))')
    expect(app).toContain('const BASE_EQUIPMENT_SLOT_COUNT = 12')
    expect(app).toContain('const EXTRA_EQUIPMENT_SLOT_COUNT = 13')
    expect(app).toContain('function equipmentSlotCount')
    expect(app).toContain('w={equipmentSlots} h={1}')
    expect(app).toContain('w={BASE_EQUIPMENT_SLOT_COUNT} h={1}')
    expect(app).toContain('格单行，战斗中默认不生效')
    expect(app).toContain('gridTemplateColumns: `repeat(${slots}, minmax(0, 1fr))`')
    expect(css).toContain('overflow-x: clip')
    expect(cssRule('.slot-grid')).toContain('gap: 8px')
    expect(cssRule('.slot-grid')).toContain('padding: 14px')
    expect(app).toContain('gridTemplateRows: `repeat(${h}, var(--board-slot-h))`')
  })

  it('lets the shop inventory work area use the wide screen while keeping shop offers readable', () => {
    expect(cssRule('.screen-content')).toContain('width: min(1920px, calc(100vw - 48px))')
    expect(css).toContain('width: min(1920px, 100%)')
    expect(css).toContain('grid-template-rows: auto 1fr')
    expect(cssRule('.shop-shelf')).toContain('width: 100%')
    expect(cssRule('.shop-shelf')).toContain('justify-self: stretch')
    expect(cssRule('.shop-shelf')).not.toContain('width: min(1280px, 100%)')
    expect(cssRule('.inventory-board')).toContain('width: 100%')
    expect(css).toContain('align-self: stretch')
    expect(cssRule('.inventory-board')).toContain('grid-template-rows: minmax(0, 1fr) minmax(0, 1fr)')
    expect(cssRule('.inventory-board.expanded .grid-panel:first-child')).toContain('align-content: start')
    expect(cssRule('.inventory-board.expanded .grid-panel:last-child')).toContain('align-content: start')
  })

  it('keeps active-run shop controls compact enough for the forfeit action to stay visible', () => {
    expect(cssRule('.shop-workbench')).toContain('min-height: calc(100vh - 170px)')
    expect(cssRule('.shop-workbench')).toContain('gap: 10px')
    expect(cssRule('.inventory-board')).toContain('padding: 10px')
    expect(cssRule('.inventory-board')).toContain('gap: 8px')
    expect(cssRule('.inventory-board.expanded .grid-panel:last-child')).toContain('align-content: start')
    expect(cssRule('.forfeit-run-action')).toContain('margin: 4px auto 0')
  })

  it('keeps the forfeit settlement copy readable over illustrated backgrounds', () => {
    expect(cssRule('.forfeit-run-action')).toContain('background: rgba(255, 250, 241, .94)')
    expect(cssRule('.forfeit-run-action')).toContain('color: var(--ink)')
    expect(cssRule('.forfeit-run-action')).toContain('border: 3px solid var(--ink)')
    expect(cssRule('.forfeit-run-action strong')).toContain('color: var(--ink)')
    expect(cssRule('.forfeit-run-action strong')).toContain('font-size: 24px')
    expect(cssRule('.forfeit-run-action strong')).toContain('font-weight: 950')
    expect(cssRule('.forfeit-run-action span')).toContain('color: rgba(61, 45, 37, .86)')
    expect(cssRule('.forfeit-run-action span')).toContain('font-size: 15px')
    expect(cssRule('.forfeit-run-action span')).toContain('font-weight: 900')
    expect(cssRule('.forfeit-run-action span')).not.toContain('color: var(--muted)')
  })

  it('keeps the left relic rail narrow and the right bag grid wide', () => {
    expect(cssRule('.bag-relic-row')).toContain('grid-template-columns: 220px minmax(0, 1fr)')
  })

  it('keeps relic slots from resizing around text content', () => {
    expect(cssRule(':root')).toContain('--relic-slot-size: 86px')
    expect(cssRule('.relic-slot-grid')).toContain('grid-template-columns: repeat(2, var(--relic-slot-size))')
    expect(cssRule('.relic-slot-grid')).toContain('grid-template-rows: repeat(3, var(--relic-slot-size))')
    expect(cssRule('.relic-slot')).toContain('aspect-ratio: 1')
    expect(cssRule('.relic-slot')).toContain('width: var(--relic-slot-size)')
    expect(cssRule('.relic-slot')).toContain('height: var(--relic-slot-size)')
    expect(cssRule('.relic-slot')).toContain('padding: 6px')
    expect(cssRule('.relic-icon-button')).toContain('width: 100%')
    expect(cssRule('.relic-icon-button')).toContain('aspect-ratio: 1')
    expect(css).not.toMatch(/\.relic-slot-grid\s*\{[^}]*grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\)/s)
    expect(cssRule('.relic-floating-tip')).toContain('width: min(320px, calc(100vw - 28px))')
    expect(cssRule('.floating-tip.relic-floating-tip')).toContain('width: min(320px, calc(100vw - 28px))')
  })

  it('uses the provided hand-drawn cream UI structure', () => {
    expect(css).toContain('--page: #fff4e4')
    expect(css).toContain('--ink: #3d2d25')
    expect(cssRule(':root')).toContain('--handdrawn-font')
    expect(cssRule(':root')).toContain('"Comic Sans MS"')
    expect(cssRule(':root')).toContain('"Microsoft YaHei"')
    expect(cssRule('body')).toContain('font-family: var(--handdrawn-font)')
    expect(cssRule('body')).toContain('font-size: 17px')
    expect(cssRule('body')).toContain('font-weight: 700')
    expect(cssRule('h1')).toContain('font-size: 24px')
    expect(app).toContain('const HANDDRAWN_FONT_STACK')
    expect(app).toContain('context.font = `950 40px ${HANDDRAWN_FONT_STACK}`')
    expect(css).toContain('border: 3px solid var(--ink)')
    expect(css).not.toContain('linear-gradient(135deg, #ffe2ae')
    expect(app).not.toContain('<PageNav')
    expect(app).not.toContain('<ChapterProgress')
  })

  it('defines a richer soft handdrawn visual system without changing style families', () => {
    expect(cssRule(':root')).toContain('--paper-fiber')
    expect(cssRule(':root')).toContain('--sketch-shadow')
    expect(cssRule(':root')).toContain('--paper-tilt-left')
    expect(cssRule(':root')).toContain('--paper-tilt-soft-right')
    expect(cssRule(':root')).toContain('--sticker-blue')
    expect(cssRule('body')).toContain('var(--paper-fiber)')
    expect(cssRule('.app-shell')).toContain('radial-gradient')
    expect(cssRule('.paper-card')).toContain('position: relative')
    expect(cssRule('.paper-card')).toContain('--paper-tilt')
    expect(cssRule('.paper-card:nth-child(3n)')).toContain('--paper-tilt')
    expect(cssRule('.paper-card:nth-child(4n)')).toContain('--paper-tilt')
    expect(cssRule('.paper-card:nth-child(5n)')).toContain('--paper-tilt')
    expect(cssRule('.paper-card::before')).toContain('transform: rotate')
    expect(cssRule('.paper-card::after')).toContain('background')
    expect(cssRule('.sticker-card::before')).toContain('content: ""')
    expect(cssRule('.sticker-card::before')).toContain('rotate')
    expect(css).not.toContain('#0b1020')
  })

  it('adds handdrawn feedback treatment for high-frequency shop and inventory actions', () => {
    expect(cssRule('.paper-inventory')).toContain('background')
    expect(cssRule('.paper-inventory .slot')).toContain('box-shadow')
    expect(cssRule('.slot.over')).toContain('outline')
    expect(cssRule('.sell-zone.over::after')).toContain('content')
    expect(cssRule('.drag-overlay-item')).not.toContain('rotate')
    expect(cssRule('.item-card.can-upgrade::after')).toContain('content')
    expect(cssRule('.upgrade-indicator')).toContain('animation')
    expect(cssRule('.paper-shop-card .price-tag')).toContain('rotate')
    expect(cssRule('.action-button:active, .primary:active, .secondary:active, .danger-button:active, .icon-button:active, .reroll-button:active')).toContain('translateY')
  })

  it('keeps drag and press feedback on cheap composited styles', () => {
    expect(cssRule('.drag-overlay-item')).toContain('position: fixed')
    expect(cssRule('.drag-overlay-item')).toContain('left: 0')
    expect(cssRule('.drag-overlay-item')).toContain('top: 0')
    expect(cssRule('.drag-overlay-item')).toContain('will-change: transform')
    expect(cssRule('.drag-overlay-item')).toContain('contain: layout paint style')
    expect(cssRule('.drag-overlay-item::before, .drag-overlay-item::after')).toContain('display: none')
    expect(cssRule('.drag-overlay-ghost')).toContain('box-shadow')
    expect(cssRule('.drag-ghost-mark')).toContain('border: 2px solid currentColor')
    expect(cssRule('.drag-source-placeholder')).toContain('opacity')
    expect(css).toContain('.drag-performance-mode .item-card::before,')
    expect(cssRule('.drag-performance-mode .item-card-icon-art')).toContain('filter: none')
    expect(cssRule('.drag-performance-mode .upgrade-indicator')).toContain('animation: none')
    expect(cssRule('.drag-performance-mode .floating-tip')).toContain('display: none')
    expect(cssRule('.item-card.dragging::before, .item-card.dragging::after')).toContain('display: none')
    expect(css).not.toContain('.item-card.input-active,')
    expect(css).not.toContain('.item-card:active')
  })

  it('keeps move-slot and battle target effects above tray skin layers', () => {
    expect(cssRule('.slot-grid')).toContain('isolation: isolate')
    expect(cssRule('.battle-slot-grid')).toContain('isolation: isolate')
    expect(cssRule('.battle-slot-grid::before, .paper-inventory .slot-grid::before')).toContain('z-index: 0')
    expect(cssRule('.paper-inventory .slot')).toContain('z-index: 1')
    expect(cssRule('.battle-slot')).toContain('z-index: 1')
    expect(cssRule('.slot.over')).toContain('z-index: 4')
    expect(cssRule('.slot.over::after')).toContain('z-index: 2')
    expect(cssRule('.battle-item-vfx-target')).toContain('z-index: 10')
    expect(cssRule('.battle-fx-stage')).toContain('z-index: 80')
  })

  it('adds handdrawn battle staging and reduced motion support', () => {
    expect(cssRule('.handdrawn-stage')).toContain('background')
    expect(cssRule('.handdrawn-stage::before')).toContain('radial-gradient')
    expect(cssRule('.handdrawn-dice')).toContain('transform')
    expect(cssRule('.battle-dog.status-poison::before')).toContain('background')
    expect(cssRule('.battle-dog.status-shield::after')).toContain('content: none')
    expect(cssRule('.battle-dog.status-shield .battle-dog-img::after')).toContain('border')
    expect(cssRule('.handdrawn-result')).toContain('animation')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    expect(cssRule('@media (prefers-reduced-motion: reduce)')).toContain('animation-duration: .001ms')
  })

  it('adds second-pass handdrawn material detail across shell, cards, battle, and tips', () => {
    expect(cssRule(':root')).toContain('--ink-wash')
    expect(cssRule(':root')).toContain('--paper-edge-highlight')
    expect(cssRule(':root')).toContain('--pressed-sketch-shadow')
    expect(cssRule('.auth-panel.paper-card')).toContain('border: 3px solid var(--ink)')
    expect(cssRule('.topbar.paper-card')).toContain('transform: none')
    expect(cssRule('.paper-card:hover::before')).toContain('border-color')
    expect(cssRule('.paper-item-card::before')).toContain('linear-gradient')
    expect(cssRule('.paper-item-card::after')).toContain('border')
    expect(cssRule('.handdrawn-fx-canvas')).toContain('mix-blend-mode')
    expect(cssRule('.handdrawn-stage::after')).toContain('background')
    expect(cssRule('.handdrawn-dice.rolling')).toContain('animation')
    expect(cssRule('.handdrawn-status-chip')).toContain('border')
    expect(cssRule('.status-chip.poison.handdrawn-status-chip')).toContain('background')
    expect(cssRule('.rule-tip.paper-card')).toContain('border: 3px solid var(--ink)')
    expect(css).toContain('@keyframes diceSketchBounce')
    expect(css).toContain('@keyframes paperShimmer')
  })

  it('keeps the real battle playback view dense and readable on narrow screens', () => {
    expect(cssRule('.visual-battle')).toContain('padding')
    expect(cssRule('.battle-toolbar')).toContain('display: grid')
    expect(cssRule('.battle-toolbar')).toContain('grid-template-columns: minmax(0, 1fr) auto')
    expect(cssRule('.battle-toolbar .speed-row')).toContain('justify-self: end')
    expect(css).toContain('.visual-battle { gap: 6px; padding: 8px; }')
    expect(css).toContain('.battle-toolbar .speed-row { width: 100%; justify-content: center; }')
    expect(css).toContain('.battle-stage { grid-template-columns: 1fr; min-height: 440px; padding: 10px; }')
    expect(css).toContain('.battle-dog-img { width: 92px; height: 92px; }')
  })

  it('keeps desktop battle playback focused on large equipment rails over empty stage space', () => {
    expect(cssRule('.visual-battle')).toContain('width: min(1920px, 100%)')
    expect(cssRule('.visual-battle')).toContain('min-height: calc(100vh - 170px)')
    expect(cssRule('.visual-battle')).toContain('margin: 0 auto')
    expect(lastCssRule('.battle-panel')).toContain('width: min(1920px, 100%)')
    expect(lastCssRule('.battle-panel')).not.toContain('width: min(1280px, 100%)')
    expect(cssRule('.visual-battle')).toContain('grid-template-rows: auto auto minmax(190px, 240px) auto auto auto')
    expect(cssRule('.battle-stage')).toContain('min-height: 190px')
    expect(cssRule('.battle-stage')).toContain('max-height: 240px')
    expect(cssRule('.battle-stage')).toContain('grid-template-columns: minmax(220px, 1fr) minmax(120px, .34fr) minmax(220px, 1fr)')
    expect(cssRule('.battle-equipment-row')).toContain('grid-template-columns: minmax(0, 1fr) auto')
    expect(cssRule('.battle-equipment-row')).toContain('align-items: stretch')
    expect(cssRule('.battle-equipment-row .relic-rail')).toContain('width: 188px')
    expect(cssRule('.battle-equipment-row .relic-slot-grid')).toContain('grid-template-columns: repeat(3, 52px)')
    expect(cssRule('.battle-equipment-row .relic-slot-grid')).toContain('grid-template-rows: repeat(2, 52px)')
    expect(cssRule('.battle-item')).toContain('min-height: 142px')
    expect(cssRule('.battle-item .item-icon')).toContain('width: 42px')
    expect(cssRule('.battle-item .item-icon')).toContain('height: 42px')
    expect(cssRule('.battle-stage .battle-dog')).toContain('grid-template-columns: minmax(170px, 260px) auto')
    expect(cssRule('.battle-stage .battle-dog .hp')).toContain('grid-row: 1 / span 2')
    expect(cssRule('.battle-stage .battle-dog-img')).toContain('width: clamp(88px, 8vw, 112px)')
    expect(cssRule('.battle-stage .battle-dog.opponent')).toContain('grid-column: 1')
    expect(cssRule('.battle-stage .battle-dice')).toContain('grid-column: 2')
    expect(cssRule('.battle-stage .battle-dog.player')).toContain('grid-column: 3')
  })

  it('shows battle dice as colored roll results without extra visible copy', () => {
    expect(primitives).not.toContain('<span>{label}</span>')
    expect(app).not.toContain("instance.presentation.kind === 'roll' ? '掷'")
    expect(app).toContain("instance.presentation.kind === 'roll' ? instance.event.roll ?? ''")
    expect(cssRule('.dynamic-dice-player .dynamic-dice-value')).toContain('color: #14532d')
    expect(cssRule('.dynamic-dice-opponent .dynamic-dice-value')).toContain('color: #7f1d1d')
    expect(cssRule('.battle-dice.rolling .dynamic-dice-value')).toContain('battleRollResultPop')
    expect(css).toContain('@keyframes battleRollResultPop')
  })

  it('keeps battle playback controls in one compact three-button row', () => {
    expect(app).toContain('className="battle-status"')
    expect(cssRule('.battle-status')).toContain('display: grid')
    expect(cssRule('.battle-status')).toContain('gap: 4px')
    expect(cssRule('.battle-toolbar > div')).toBe('')
    expect(cssRule('.battle-toolbar .speed-row')).toContain('display: grid')
    expect(cssRule('.battle-toolbar .speed-row')).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(cssRule('.battle-toolbar .speed-row')).toContain('width: auto')
    expect(cssRule('.battle-stage')).toContain('min-height: 190px')
  })

  it('adds third-pass handdrawn detail to the shop, inventory, and dog selection surfaces', () => {
    expect(cssRule('.shop-shelf.sketch-panel::before')).toContain('content: ""')
    expect(cssRule('.shop-shelf.sketch-panel')).toContain('box-shadow: none')
    expect(cssRule('.shop-shelf.sketch-panel::after')).toContain('radial-gradient')
    expect(cssRule('.offer-row')).toContain('align-items: stretch')
    expect(cssRule('.offer-row')).toContain('gap: 12px')
    expect(cssRule('.paper-shop-card')).toContain('transform-origin')
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-tone')
    expect(cssRule('.offer-row .paper-shop-card:nth-child(4)')).toContain('--paper-tilt')
    expect(cssRule('.offer-row .paper-shop-card:nth-child(5)')).toContain('--shop-paper-cut')
    expect(cssRule('.paper-shop-card:hover')).toContain('rotate(var(--paper-tilt))')
    expect(cssRule('.paper-shop-card:hover .item-card-icon-art')).toContain('rotate')
    expect(cssRule('.shop-card-unaffordable')).toContain('filter: grayscale(.82) brightness(.68) saturate(.55)')
    expect(cssRule('.shop-card-unaffordable:hover')).toContain('transform: none')
    expect(cssRule('.shop-card-owned')).toContain('border-color')
    expect(cssRule('.owned-badge')).toContain('position: absolute')
    expect(cssRule('.paper-inventory .slot-grid::before')).toContain('linear-gradient(90deg')
    expect(cssRule('.paper-inventory .grid-heading h3::after')).toContain('content: ""')
    expect(cssRule('.paper-dog-card .dog-art-frame')).toContain('position: relative')
    expect(cssRule('.paper-dog-card .dog-art-frame::after')).toContain('border')
    expect(cssRule('.paper-dog-card.selected')).toContain('var(--selection-wash)')
    expect(cssRule('.dog-card-grid')).toContain('align-items: stretch')
  })

  it('keeps shop cards as brown-edged paper notes instead of thick quality frames', () => {
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-edge-ink: rgba(61, 45, 37, .74)')
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-edge-width: 1.75px')
    expect(cssRule('.paper-shop-card')).toContain('--shop-quality-glow')
    expect(cssRule('.paper-shop-card')).toContain('border: 0')
    expect(cssRule('.paper-shop-card')).toContain('filter: var(--shop-paper-filter)')
    expect(cssRule('.paper-shop-card::before')).toContain('inset: 0')
    expect(cssRule('.paper-shop-card::before')).toContain('inset 0 0 0 var(--shop-paper-edge-width) var(--shop-paper-edge-ink)')
    expect(cssRule('.paper-shop-card::before')).toContain('filter: var(--shop-paper-filter)')
    expect(cssRule('.paper-shop-card::before')).toContain('clip-path: var(--shop-paper-cut)')
    expect(cssRule('.paper-shop-card::after')).toContain('clip-path: var(--shop-paper-cut)')
    expect(css).not.toMatch(/\.item-card\.quality-bronze,\s*\.shop-card\.quality-bronze,\s*\.tip-tag\.quality-bronze\s*\{[^}]*border-width:\s*5px/s)
    expect(css).not.toMatch(/\.item-card\.quality-silver,\s*\.shop-card\.quality-silver,\s*\.tip-tag\.quality-silver\s*\{[^}]*border-width:\s*5px/s)
    expect(css).not.toMatch(/\.paper-shop-card\.quality-bronze,\s*\.paper-shop-card\.quality-silver,\s*\.paper-shop-card\.quality-gold,\s*\.paper-shop-card\.quality-diamond\s*\{[^}]*border:/s)
  })

  it('uses stronger quality glow on shop paper edges without replacing the brown edge', () => {
    expect(cssRule('.paper-shop-card.quality-bronze')).toContain('--shop-quality-glow: rgba(194, 91, 34, .78)')
    expect(cssRule('.paper-shop-card.quality-silver')).toContain('--shop-quality-glow: rgba(207, 224, 236, .86)')
    expect(cssRule('.paper-shop-card.quality-gold')).toContain('--shop-quality-glow: rgba(255, 207, 66, 1)')
    expect(cssRule('.paper-shop-card.quality-diamond')).toContain('--shop-quality-glow: rgba(102, 231, 255, 1)')
    expect(cssRule('.paper-shop-card.quality-gold')).not.toContain('border-width: 5px')
    expect(cssRule('.paper-shop-card.quality-diamond')).not.toContain('border-width: 5px')
    expect(cssRule('.paper-shop-card:hover')).toContain('filter: var(--shop-paper-filter-hover)')
    expect(cssRule('.paper-shop-card.selected')).toContain('filter: var(--shop-paper-filter-hover)')
    expect(cssRule('.paper-shop-card.shop-card-unaffordable')).toContain('filter: grayscale(.82) brightness(.68) saturate(.55) drop-shadow')
    expect(cssRule('.paper-shop-card.shop-card-unaffordable:hover')).toContain('filter: grayscale(.82) brightness(.68) saturate(.55) drop-shadow')
  })

  it('lays out shop cards as compact wide tickets with fixed artwork', () => {
    expect(app).toContain('className="shop-card-meta"')
    expect(cssRule('.shop-card')).toContain('grid-template-areas')
    expect(cssRule('.shop-card')).toContain('"quality title"')
    expect(cssRule('.shop-card')).toContain('"price description"')
    expect(cssRule('.shop-card')).toContain('grid-template-columns: 58px minmax(0, 1fr)')
    expect(cssRule('.shop-card')).toContain('min-height: 138px')
    expect(cssRule('.shop-card-main')).toContain('grid-area: title')
    expect(cssRule('.shop-card-meta')).toContain('grid-area: meta')
    expect(cssRule('.shop-quality-chip')).toContain('grid-area: quality')
    expect(cssRule('.shop-card > .effect-line')).toContain('grid-area: description')
    expect(cssRule('.shop-card > .price-tag')).toContain('grid-area: price')
    expect(cssRule('.shop-card-art')).toContain('width: 52px')
    expect(cssRule('.shop-card-art')).toContain('height: 52px')
    expect(cssRule('.shop-card-art .item-card-icon-art')).toContain('width: 40px')
    expect(lastCssRule('.paper-shop-card.shop-card')).toContain('grid-template-areas')
    expect(lastCssRule('.paper-shop-card.shop-card .effect-line')).toContain('min-height: 38px')
  })

  it('keeps shop note edge strokes uniform while layering quality glow above the paper skin', () => {
    expect(cssRule('.paper-shop-card')).toContain('--shop-quality-glow-ring')
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-shadow: var(--shop-quality-glow-ring)')
    expect(cssRule('.paper-shop-card')).not.toContain('--shop-paper-shadow: var(--paper-edge-stroke)')
    expect(cssRule('.paper-shop-card::before')).toContain('z-index: 1')
    expect(cssRule('.paper-shop-card::after')).toContain('z-index: 1')
    expect(cssRule('.paper-shop-card > *')).toContain('z-index: 2')
    expect(cssRule('.paper-shop-card:hover')).not.toContain('var(--paper-edge-stroke)')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card::before')).toContain('box-shadow: var(--shop-paper-shadow)')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card::before')).toContain('-webkit-mask: none')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card::after')).toContain('animation: none')
  })

  it('gives shop paper notes visible depth without changing their note silhouette', () => {
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-contact-shadow')
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-depth-filter')
    expect(cssRule('.paper-shop-card')).toContain('var(--shop-paper-contact-shadow)')
    expect(cssRule('.paper-shop-card')).toContain('filter: var(--shop-paper-filter)')
    expect(cssRule('.paper-shop-card::before')).toContain('inset 0 -7px 0 rgba(112, 72, 30, .16)')
    expect(cssRule('.paper-shop-card:hover')).toContain('--shop-paper-contact-shadow-hover')
    expect(cssRule('.paper-shop-card:hover')).toContain('filter: var(--shop-paper-filter-hover)')
  })

  it('adds two extra randomized paper styles to shop choice tabs', () => {
    expect(cssRule('.shop-choice-screen .choice-grid')).toContain('perspective')
    expect(cssRule('.shop-choice-screen .choice')).toContain('--choice-tab-contact-shadow')
    expect(cssRule('.shop-choice-screen .choice')).toContain('rotateX(var(--choice-tab-lift))')
    expect(cssRule('.shop-choice-screen .choice:nth-child(4n)')).toContain('--choice-tab-cut')
    expect(cssRule('.shop-choice-screen .choice:nth-child(4n)')).toContain('--choice-tab-contact-shadow')
    expect(cssRule('.shop-choice-screen .choice:nth-child(5n)')).toContain('--choice-tab-cut')
    expect(cssRule('.shop-choice-screen .choice:nth-child(5n)')).toContain('--choice-tab-paper')
    expect(cssRule('.shop-choice-screen .choice.placeholder')).toContain('transform: none')
  })

  it('adds two more shop paper card silhouettes while preserving quality glow depth', () => {
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-depth-filter-hover')
    expect(cssRule('.paper-shop-card')).toContain('--shop-paper-contact-shadow')
    expect(cssRule('.paper-shop-card')).toContain('--shop-quality-glow-ring')
    expect(cssRule('.offer-row .paper-shop-card:nth-child(6n + 2)')).toContain('--shop-paper-cut')
    expect(cssRule('.offer-row .paper-shop-card:nth-child(6n + 2)')).toContain('--shop-paper-contact-shadow')
    expect(cssRule('.offer-row .paper-shop-card:nth-child(6n + 5)')).toContain('--shop-paper-cut')
    expect(cssRule('.offer-row .paper-shop-card:nth-child(6n + 5)')).toContain('--shop-paper-tone')
    expect(cssRule('.paper-shop-card:hover::before')).toContain('var(--shop-paper-shadow-hover)')
  })

  it('renders shop quality glow from the clipped paper outline instead of the host rectangle', () => {
    expect(cssRule('.paper-shop-card')).not.toContain('clip-path: var(--shop-paper-cut')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card')).toContain('background: transparent')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card')).toContain('box-shadow: none')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card::before')).toContain('clip-path: var(--shop-paper-cut')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card::before')).toContain('box-shadow: var(--shop-paper-shadow)')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card::before')).toContain('filter: var(--shop-paper-filter)')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card:hover::before')).toContain('filter: var(--shop-paper-filter-hover)')
    expect(lastCssRule('.paper-shop-card.paper-item-card.item-card.selected::before')).toContain('filter: var(--shop-paper-filter-hover)')
  })

  it('adds visible quality glow behind inventory equipment cards inside the shop', () => {
    expect(cssRule('.inventory-board .paper-item-card.item-card')).toContain('--inventory-quality-glow')
    expect(cssRule('.inventory-board .paper-item-card.item-card')).toContain('box-shadow: var(--inventory-quality-shadow)')
    expect(cssRule('.inventory-board .paper-item-card.item-card.quality-bronze')).toContain('--inventory-quality-glow: rgba(194, 91, 34, .82)')
    expect(cssRule('.inventory-board .paper-item-card.item-card.quality-silver')).toContain('--inventory-quality-glow: rgba(207, 224, 236, .92)')
    expect(cssRule('.inventory-board .paper-item-card.item-card.quality-gold')).toContain('--inventory-quality-glow: rgba(255, 207, 66, 1)')
    expect(cssRule('.inventory-board .paper-item-card.item-card.quality-diamond')).toContain('--inventory-quality-glow: rgba(102, 231, 255, 1)')
    expect(cssRule('.inventory-board .paper-item-card.item-card.selected')).toContain('var(--inventory-quality-shadow-strong)')
  })

  it('adds fourth-pass handdrawn detail to history, tips, relics, and reward choices', () => {
    expect(cssRule('.player-history-panel::before')).toContain('content: ""')
    expect(cssRule('.history-summary')).toContain('grid-template-columns')
    expect(cssRule('.history-ladder-slot')).toContain('min-height')
    expect(cssRule('.dog-rank-trophy')).toContain('position: relative')
    expect(cssRule('.history-run-row::before')).toContain('linear-gradient')
    expect(cssRule('.history-open-action')).toContain('var(--pressed-sketch-shadow)')
    expect(cssRule('.floating-tip.paper-card::before')).toContain('content: ""')
    expect(cssRule('.tip-dice span')).toContain('box-shadow')
    expect(cssRule('.relic-slot-grid::before')).toContain('radial-gradient')
    expect(cssRule('.relic-slot::after')).toContain('border')
    expect(cssRule('.relic-icon-button[aria-pressed="true"]')).toContain('var(--selection-wash)')
    expect(cssRule('.reward-panel.paper-card::before')).toContain('content: ""')
    expect(cssRule('.reward-choice.selected')).toContain('var(--selection-wash)')
  })

  it('adds fifth-pass handdrawn feedback detail to controls, logs, and history overlays', () => {
    expect(css).toMatch(/\.action-button::after,[\s\S]*\.log-toggle::after\s*\{[\s\S]*content: ""/)
    expect(css).toMatch(/\.action-button:hover,[\s\S]*\.log-toggle:hover\s*\{[\s\S]*rotate/)
    expect(cssRule('.speed-row .active::after')).toContain('content: ""')
    expect(cssRule('.battle-log::before')).toContain('var(--paper-fiber)')
    expect(cssRule('.battle-log p::before')).toContain('content: ""')
    expect(cssRule('.battle-log p.system::before')).toContain('#ffe08a')
    expect(cssRule('.player-history-page::before')).toContain('radial-gradient')
    expect(cssRule('.history-detail-row.selected::before')).toContain('var(--selection-wash)')
    expect(cssRule('.history-empty-state::before')).toContain('border')
  })

  it('keeps historical equipment previews bounded inside the run detail panel', () => {
    expect(cssRule('.history-equipment-preview')).toContain('--slot-h: 82px')
    expect(cssRule('.history-equipment-preview .battle-slot-grid')).toContain('overflow: hidden')
    expect(cssRule('.history-equipment-preview .battle-item')).toContain('overflow: hidden')
    expect(cssRule('.history-equipment-preview .item-effect')).toContain('display: none')
    expect(cssRule('.history-equipment-preview .item-card-icon-art')).toContain('width: 34px')
  })

  it('presents apex equipment details in a wide callout overlay', () => {
    expect(cssRule('.apex-config-overlay')).toContain('position: fixed')
    expect(cssRule('.apex-config-overlay')).toContain('z-index: var(--z-modal-overlay)')
    expect(cssRule('.apex-config-sheet')).toContain('width: min(1040px, calc(100vw - 36px))')
    expect(cssRule('.apex-config-sheet')).toContain('grid-template-rows: auto minmax(0, 1fr)')
    expect(cssRule('.apex-equipment-preview')).toContain('--slot-h: 104px')
    expect(cssRule('.apex-equipment-preview .battle-slot-grid')).toContain('overflow: hidden')
    expect(cssRule('.apex-equipment-preview .battle-item')).toContain('overflow: hidden')
    expect(cssRule('.apex-equipment-preview .item-effect')).toContain('display: none')
    expect(cssRule('.apex-equipment-preview .item-card-icon-art')).toContain('width: 46px')
  })

  it('adds battle vfx causality styling for triggers, targets, and handwritten feedback', () => {
    expect(cssRule('.visual-battle')).toContain('position: relative')
    expect(cssRule('.battle-fx-stage')).toContain('position: absolute')
    expect(cssRule('.battle-fx-stage')).toContain('inset: 0')
    expect(cssRule('.battle-feedback-burst')).toContain('animation')
    expect(cssRule('.battle-log p.active-feedback')).toContain('background')
    expect(cssRule('.feedback-layer')).toContain('pointer-events: none')
    expect(cssRule('.ui-feedback-toast')).toContain('animation')
    expect(cssRule('.ui-feedback-toast.danger')).toContain('border-color')
    expect(cssRule('.ui-feedback-toast.success')).toContain('border-color')
    expect(cssRule('.feedback-flash-success')).toContain('animation')
    expect(cssRule('.feedback-flash-danger')).toContain('animation')
    expect(cssRule('.battle-item-trigger')).toContain('animation')
    expect(cssRule('.battle-item-trigger::after')).toContain('content: ""')
    expect(app).toContain('itemTriggerCountLabel(events, owner, item.id, displayIndex)')
    expect(app).toContain('className={`trigger-count-stamp')
    expect(cssRule('.trigger-count-stamp')).toContain('bottom: -18px')
    expect(cssRule('.battle-slot-grid')).toContain('padding: 9px 9px 28px')
    expect(cssRule('.battle-item.trigger-count-pop .trigger-count-stamp')).toContain('animation')
    expect(css).toContain('@keyframes triggerCountStampPop')
    expect(cssRule('.battle-dog.vfx-target-damage .battle-dog-img')).toContain('filter')
    expect(cssRule('.battle-dog.vfx-target-heal .battle-dog-img')).toContain('drop-shadow')
    expect(cssRule('.battle-dog.vfx-target-shield .battle-dog-img::after')).toContain('content: ""')
    expect(cssRule('.battle-dog.vfx-target-shield .hp::after')).toBe('')
    expect(cssRule('.battle-dog.vfx-target-poison .battle-dog-img')).toContain('saturate')
    expect(cssRule('.battle-dog.vfx-target-weak .battle-dog-img')).toContain('hue-rotate')
    expect(cssRule('.battle-dog.vfx-target-freeze .battle-dog-img')).toContain('drop-shadow')
    expect(css).toContain('@keyframes battleTriggerStamp')
    expect(css).toContain('@keyframes vfxDamageJolt')
  })

  it('keeps battle trigger counts outside equipment cards with reserved row space', () => {
    expect(cssRule('.battle-equipment-row')).toContain('--slot-h: 142px')
    expect(cssRule('.battle-item')).toContain('min-height: 142px')
    expect(cssRule('.battle-item')).toContain('overflow: visible')
    expect(cssRule('.battle-item')).toContain('isolation: isolate')
    expect(cssRule('.battle-slot-grid')).toContain('padding: 9px 9px 28px')
    expect(lastCssRule('.battle-slot-grid')).toContain('padding: 10px 10px 30px')
    expect(cssRule('.trigger-count-stamp')).toContain('bottom: -18px')
    expect(cssRule('.trigger-count-stamp')).toContain('z-index: 6')
    expect(cssRule('.trigger-count-stamp')).toContain('white-space: nowrap')
    expect(css).toContain('.battle-equipment-row { --slot-w: 58px; --slot-h: 104px; }')
    expect(css).toContain('.battle-item { min-height: 104px; }')
    expect(css).toContain('.battle-slot-grid { gap: 5px; padding: 10px 10px 30px; }')
  })

  it('keeps explanatory copy separated from nearby headings', () => {
    for (const selector of ['.auth-panel .brand-block > div', '.section-title > div', '.battle-status']) {
      const rule = cssRule(selector)
      expect(rule).toContain('display: grid')
      expect(rule).toContain(selector === '.battle-status' ? 'gap: 4px' : 'gap: 6px')
    }
    expect(cssRule('.battle-toolbar p')).not.toContain('margin-top')
  })

  it('keeps rule text as an inline flow inside cards and tips', () => {
    expect(cssRule('.rule-term-wrap')).toContain('display: contents')
    expect(cssRule('.rule-term')).toContain('display: inline')
    expect(cssRule('.rule-term')).toContain('white-space: nowrap')
    expect(cssRule('.rule-term')).toContain('overflow-wrap: normal')
    expect(css).not.toContain('.choice > span:last-of-type')

    for (const selector of ['.choice-copy, .card-copy', '.shop-card .effect-line', '.item-effect', '.tip-description']) {
      const rule = cssRule(selector)
      expect(rule).toContain('min-width: 0')
      expect(rule).toContain('line-height')
      expect(rule).toContain('word-break: normal')
      expect(rule).toContain('overflow-wrap: break-word')
    }
  })

  it('keeps game headings and hints readable when the system prefers dark mode', () => {
    expect(cssRule(':root')).toContain('color-scheme: light')
    expect(cssRule('h1, h2, h3')).toContain('color: var(--ink)')
    expect(cssRule('p, small')).toContain('color: var(--muted)')
    expect(cssRule('.screen-heading p')).toContain('color: var(--muted)')
    expect(cssRule('.battle-toolbar p')).toContain('color: var(--muted)')
  })

  it('styles the class reward awakening ceremony as a distinct special round surface', () => {
    expect(cssRule('.class-reward-ceremony')).toContain('min-height')
    expect(cssRule('.ceremony-stage')).toContain('animation')
    expect(cssRule('.ceremony-dog-avatar')).toContain('width')
    expect(cssRule('.ceremony-reward-preview')).toContain('grid-template-columns')
    expect(cssRule('.ceremony-skip-hint')).toContain('letter-spacing: 0')
  })

  it('keeps ceremony manuscript art inside the selection frame layer', () => {
    expect(cssRule('.class-reward-ceremony.surprise-surface::before, .class-reward-ceremony.surprise-surface::after')).toContain('content: none')
    expect(cssRule('.class-reward-ceremony.surprise-surface .ceremony-stage')).toContain('overflow: hidden')
    expect(cssRule('.class-reward-ceremony.surprise-surface .ceremony-stage::before')).toContain('var(--surprise-bg)')
    expect(cssRule('.class-reward-ceremony.surprise-surface .ceremony-stage::before')).toContain('background-size: cover, cover, auto 142%')
    expect(cssRule('.class-reward-ceremony.surprise-surface .ceremony-stage::before')).toContain('background-position: center, center, center 48%')
    expect(cssRule('.class-reward-ceremony.surprise-surface .ceremony-stage > *')).toContain('z-index: 1')
  })

  it('uses stronger parchment contrast on awakening and settlement manuscript pages', () => {
    expect(cssRule('.class-reward-ceremony.surprise-surface .ceremony-stage::after')).toContain('rgba(255, 248, 226, .62)')
    expect(cssRule('.ceremony-copy h2')).toContain('color: #2b1f19')
    expect(cssRule('.ceremony-copy p')).toContain('color: rgba(43, 31, 25, .94)')
    expect(cssRule('.ceremony-reward-chip')).toContain('background: rgba(255, 251, 241, .92)')
    expect(cssRule('.settlement-page.surprise-surface::before')).toContain('background-size: cover, cover, auto 132%')
    expect(cssRule('.settlement-card h2')).toContain('color: #2b1f19')
    expect(cssRule('.settlement-card > p')).toContain('color: rgba(43, 31, 25, .9)')
    expect(lastCssRule('.settlement-score-grid small')).toContain('color: rgba(43, 31, 25, .82)')
  })

  it('presents completed run settlement as a full-screen overlay with top-right visibility controls', () => {
    expect(cssRule('.settlement-page')).toContain('position: fixed')
    expect(cssRule('.settlement-page')).toContain('inset: 0')
    expect(cssRule('.settlement-page')).toContain('z-index')
    expect(lastCssRule('.settlement-page')).toContain('left: 50%')
    expect(lastCssRule('.settlement-page')).toContain('right: auto')
    expect(lastCssRule('.settlement-page')).toContain('transform: translateX(-50%)')
    expect(lastCssRule('.settlement-page')).toContain('max-width: 1280px')
    expect(cssRule('.settlement-hide-button')).toContain('position: absolute')
    expect(cssRule('.settlement-hide-button')).toContain('top: clamp')
    expect(cssRule('.settlement-show-button')).toContain('position: fixed')
    expect(cssRule('.settlement-show-button')).toContain('right: clamp')
  })

  it('lays out dogfight as an autochess room with ranked player frames and phase controls', () => {
    expect(cssRule('.dogfight-phase-track')).toContain('grid-template-columns')
    expect(cssRule('.dogfight-survivor-board')).toContain('display: grid')
    expect(cssRule('.dogfight-player-frame')).toContain('grid-template-columns')
    expect(cssRule('.dogfight-player-frame.selected')).toContain('outline')
    expect(cssRule('.dogfight-player-frame.bot')).toContain('border-style: dashed')
    expect(cssRule('.dogfight-battle-dock')).toContain('display: grid')
    expect(cssRule('.dogfight-room-columns')).toContain('grid-template-columns')
  })

  it('makes player apex leaderboard entries easy to find', () => {
    expect(app).toContain('isMine: boolean')
    expect(app).toContain("entry.isMine ? 'player-entry' : ''")
    expect(app).toContain('{entry.isMine && <span className="apex-self-marker">我的记录</span>}')
    expect(app).toContain('className="apex-self-marker"')
    expect(app).toContain('我的记录')
    expect(cssRule('.apex-rank-row.player-entry')).toContain('border: 3px solid')
    expect(cssRule('.apex-rank-row.player-entry')).toContain('box-shadow')
    expect(cssRule('.apex-rank-row.player-entry::before')).toContain('content: "我的记录"')
    expect(cssRule('.apex-self-marker')).toContain('background')
    expect(cssRule('.apex-self-marker')).toContain('font-weight: 950')
  })

  it('stacks dogfight room columns on narrow screens', () => {
    expect(css).toContain('.dogfight-layout,')
    expect(css).toContain('.dogfight-room-columns {')
    expect(css).toContain('.dogfight-room-card {')
    expect(css).toContain('grid-template-columns: 1fr')
  })

  it('stacks choice cards on narrow screens so card copy is not clipped', () => {
    expect(css).toContain('@media (max-width: 760px)')
    expect(css).toContain('.choice-grid { grid-template-columns: 1fr; }')
  })

  it('styles clickable battle status chips and their compact tips without resizing rows', () => {
    expect(cssRule('.status-chip')).toContain('appearance: none')
    expect(cssRule('.status-chip')).toContain('cursor: pointer')
    expect(cssRule('.status-chip')).toContain('font-family: inherit')
    expect(cssRule('.status-chip:hover, .status-chip:focus-visible')).toContain('transform: translateY(-1px)')
    expect(cssRule('.status-floating-tip')).toContain('width: min(320px, calc(100vw - 28px))')
    expect(cssRule('.status-tip-title')).toContain('display: flex')
    expect(cssRule('.status-tip-description')).toContain('line-height: 1.55')
  })

  it('adds stable dog brawl town visual themes across battle, shop, inventory, rewards, and results', () => {
    expect(existsSync(dogBrawlTownBackgroundUrl)).toBe(true)
    expect(statSync(dogBrawlTownBackgroundUrl).size).toBeLessThanOrEqual(1_200_000)
    expect(app).toContain('/assets/backgrounds/dog-brawl-town.jpg')
    expect(css).toContain('/assets/backgrounds/dog-brawl-town.jpg')
    expect(app).not.toContain('/assets/backgrounds/dog-brawl-town.png')
    expect(css).not.toContain('/assets/backgrounds/dog-brawl-town.png')
    expect(app).not.toContain('/assets/backgrounds/storybook-dog-park.webp')
    expect(app).not.toContain('/assets/backgrounds/storybook-back-alley.webp')
    expect(app).not.toContain('/assets/backgrounds/storybook-royal-kennel.webp')

    expect(app).toContain("type VisualThemeId = 'dogPark' | 'backAlley' | 'royalKennel'")
    expect(app).toContain('function visualThemeForRound(round: number): VisualThemeId')
    expect(app).toContain('visualThemeForRound(run.round)')
    expect(app).toContain('data-visual-theme={visualTheme}')
    expect(app).toContain('visual-theme-${visualTheme}')
    expect(cssRule('.visual-theme-surface')).toContain('--theme-bg')
    expect(cssRule('.visual-theme-surface::before')).toContain('background-image')
    expect(cssRule('.battle-stage.visual-theme-surface::before')).toContain('background-image')
    expect(cssRule('.shop-shelf.visual-theme-surface::before')).toContain('background-image')
    expect(cssRule('.inventory-board.visual-theme-surface::before')).toContain('background-image')
    expect(cssRule('.reward-panel.visual-theme-surface::before')).toContain('background-image')
    expect(cssRule('.handdrawn-result.visual-theme-surface::before')).toContain('background-image')
  })

  it('uses the dog brawl town illustration as the readable full-page background', () => {
    expect(existsSync(dogBrawlTownBackgroundUrl)).toBe(true)
    expect(statSync(dogBrawlTownBackgroundUrl).size).toBeLessThanOrEqual(1_200_000)
    expect(css).toContain('/assets/backgrounds/dog-brawl-town.jpg')
    expect(css).not.toContain('/assets/backgrounds/dog-brawl-town.png')
    expect(cssRule(':root')).toContain('--app-illustration-bg')
    expect(cssRule('.auth-shell')).toContain('var(--app-illustration-bg)')
    expect(cssRule('.app-shell')).toContain('var(--app-illustration-bg)')
    expect(cssRule('.app-shell')).toContain('background-size: cover')
    expect(cssRule('.app-shell')).toContain('background-position: center')
    expect(cssRule('.app-shell::before')).toContain('background')
    expect(cssRule('.app-shell::before')).toContain('rgba(255, 250, 241, .34)')
    expect(cssRule('.app-shell > *')).toContain('z-index: 1')
    expect(cssRule('.topbar')).toContain('rgba(255, 250, 241, .78)')
    expect(cssRule('.screen-content')).toContain('position: relative')
  })

  it('lets the dog brawl town background show through the main play surfaces', () => {
    expect(css).toMatch(/\.auth-panel,[\s\S]*\.floating-tip\s*\{[\s\S]*rgba\(255, 250, 241, \.78\)/)
    expect(cssRule('.mode-card')).toContain('rgba(255, 250, 241, .72)')
    expect(cssRule('.mode-card.available')).toContain('rgba(255, 250, 241, .68)')
    expect(cssRule('.player-history-panel')).toContain('rgba(255, 250, 241, .72)')
    expect(cssRule('.auth-panel.paper-card')).toContain('rgba(255, 250, 241, .76)')
    expect(cssRule('.topbar.paper-card')).toContain('rgba(255, 250, 241, .74)')
    expect(cssRule('.visual-theme-surface')).toContain('--theme-bg-opacity: .2')
    expect(cssRule('.visual-theme-surface::before')).toContain('rgba(255, 250, 241, .42)')
    expect(cssRule('.shop-shelf.visual-theme-surface::before')).toContain('rgba(255, 250, 241, .46)')
    expect(cssRule('.inventory-board.visual-theme-surface::before')).toContain('rgba(255, 250, 241, .52)')
    expect(cssRule('.reward-panel.visual-theme-surface::before')).toContain('rgba(255, 250, 241, .48)')
  })

  it('upgrades full-flow feedback to high-impact but bounded visual effects', () => {
    expect(app).toContain('high-impact-vfx')
    expect(cssRule('.high-impact-vfx .battle-feedback-burst')).toContain('animation')
    expect(cssRule('.high-impact-vfx .battle-item-trigger')).toContain('highImpactTrigger')
    expect(cssRule('.battle-dog.vfx-target-damage::after')).toContain('highImpactHitFlash')
    expect(cssRule('.ui-feedback-toast[data-feedback-kind="buy-success"]')).toContain('highImpactRewardPop')
    expect(cssRule('.ui-feedback-toast[data-feedback-kind="place-failed"]')).toContain('highImpactRejectShake')
    const selectedChoiceMark = cssRule('.choice.selected::after, .reward-choice.selected::after')
    expect(selectedChoiceMark).toContain('content')
    expect(selectedChoiceMark).toContain('dogPawMarkPop')
    expect(selectedChoiceMark).toContain('radial-gradient')
    expect(selectedChoiceMark).not.toContain('border-radius: 999px')
    expect(css).toContain('@keyframes highImpactTrailPulse')
    expect(css).toContain('@keyframes highImpactHitFlash')
    expect(css).toContain('@keyframes highImpactRewardPop')
    expect(css).toContain('@keyframes highImpactRejectShake')
    expect(cssRule('@media (prefers-reduced-motion: reduce)')).toContain('.visual-theme-surface::before')
  })

  it('adds meteor-quality battle equipment vfx styling and reduced-motion fallbacks', () => {
    expect(cssRule('.visual-battle')).toContain('overflow: hidden')
    expect(cssRule('.battle-fx-stage')).toContain('z-index: 80')
    expect(cssRule('.battle-item-vfx-target')).toContain('meteorTargetPulse')
    expect(cssRule('.battle-item-vfx-target::after')).toContain('meteorTargetSweep')
    expect(cssRule('.battle-item-trigger')).toContain('meteorSourcePulse')
    expect(cssRule('.battle-dog.vfx-target-shield .battle-dog-img::after')).toContain('meteorImpactGlow')
    expect(cssRule('.battle-dog.vfx-target-heal .hp::after')).toContain('meteorImpactGlow')
    expect(css).toContain('@keyframes meteorSourcePulse')
    expect(css).toContain('@keyframes meteorTargetPulse')
    expect(css).toContain('@keyframes meteorTargetSweep')
    expect(css).toContain('@keyframes meteorImpactGlow')
    expect(cssRule('@media (prefers-reduced-motion: reduce)')).toContain('.battle-item-vfx-target')
  })

  it('keeps meteor projectile canvas above battle rows and paper surfaces', () => {
    expect(cssRule('.visual-battle')).toContain('isolation: isolate')
    expect(cssRule('.battle-equipment-row')).toContain('z-index: 1')
    expect(cssRule('.battle-stage')).toContain('z-index: 1')
    expect(cssRule('.battle-fx-stage')).toContain('z-index: 80')
    expect(cssRule('.battle-fx-stage')).toContain('overflow: visible')
    expect(cssRule('.battle-fx-canvas')).toContain('z-index: 2')
    expect(cssRule('.battle-fx-canvas')).toContain('mix-blend-mode: normal')
    expect(cssRule('.battle-feedback-burst')).toContain('z-index: 3')
  })

  it('styles the battle review dashboard and categorized log filters as compact paper surfaces', () => {
    expect(cssRule('.battle-review-dashboard')).toContain('grid-template-columns')
    expect(cssRule('.battle-review-dashboard')).toContain('var(--paper-fiber)')
    expect(cssRule('.battle-review-side-grid')).toContain('grid-template-columns')
    expect(cssRule('.battle-review-side-card.player')).toContain('border-color')
    expect(cssRule('.battle-review-side-card.opponent')).toContain('border-color')
    expect(cssRule('.battle-review-metric')).toContain('min-width: 0')
    expect(cssRule('.battle-review-top-item')).toContain('border')
    expect(cssRule('.battle-log-filters')).toContain('flex-wrap: wrap')
    expect(cssRule('.battle-log-filter.active')).toContain('box-shadow')
    expect(cssRule('@media (max-width: 720px)')).toContain('.battle-review-side-grid')
    expect(cssRule('@media (prefers-reduced-motion: reduce)')).toContain('.battle-log-filter')
  })

  it('adds ornate border, manuscript, hud, and paper-bounce polish for the refined handdrawn direction', () => {
    expect(cssRule(':root')).toContain('--ornament-ink')
    expect(cssRule(':root')).toContain('--ornament-ink: rgba(')
    expect(cssRule(':root')).toContain('--ornament-ink-soft')
    expect(cssRule(':root')).toContain('--pencil-mark')
    expect(cssRule(':root')).toContain('--paper-bounce-distance')
    expect(cssRule(':root')).toContain('--edge-ornament-size')
    expect(cssRule('.paper-card::before')).toContain('var(--ornament-corner)')
    expect(cssRule('.paper-card::after')).toContain('var(--paper-grain)')
    expect(cssRule('.choice.selected, .reward-choice.selected, .shop-card.selected')).toContain('paperSelectBounce')
    expect(cssRule('.topbar')).toContain('var(--hud-paper)')
    expect(cssRule('.topbar::after')).toContain('var(--ornament-scroll)')
    expect(cssRule('.screen-heading.centered::before')).toContain('var(--banner-ribbon)')
    expect(cssRule('.screen-heading.centered::before')).toContain('height: 13px')
    expect(cssRule('.screen-heading.centered::before')).not.toContain('clip-path')
    expect(cssRule('.resource-pill::after, .dog-trait-summary::after, .speed-row button::after')).toContain('var(--pencil-mark)')
    expect(cssRule('.shop-shelf::after, .inventory-board::after, .battle-stage::after, .reward-panel::after')).toContain('var(--manuscript-lines)')
    expect(cssRule('.shop-shelf::after, .inventory-board::after, .battle-stage::after, .reward-panel::after')).toContain('opacity: .12')
    expect(cssRule('.paper-card::before')).toContain('opacity: .72')
    expect(cssRule('.action-button:active, .primary:active, .secondary:active, .danger-button:active, .icon-button:active, .reroll-button:active, .log-toggle:active')).toContain('var(--paper-bounce-distance)')
    expect(cssRule('.shop-card-unaffordable:active, .action-button:disabled:active')).toContain('invalidSketchShake')
    expect(cssVariableValue('--ornament-corner')).not.toContain('linear-gradient')
    expect(css).toContain('@keyframes paperSelectBounce')
    expect(css).toContain('@keyframes inkRedraw')
    expect(css).toContain('@keyframes invalidSketchShake')
  })

  it('keeps nested rule tips from retriggering generic selected paper-card scale motion', () => {
    expect(cssRule('.paper-card.selected, .choice.selected, .reward-choice.selected, .shop-card.selected')).toBe('')
    expect(cssRule('.choice.selected, .reward-choice.selected, .shop-card.selected')).toContain('paperSelectBounce')
  })

  it('enhances item quality borders with frame-only material and shimmer effects', () => {
    expect(cssRule('.item-card')).toContain('--quality-frame-width: 3px')
    expect(cssRule('.item-card')).toContain('border: var(--quality-frame-width) solid')
    expect(cssRule('.item-card::before')).toContain('inset: 0')
    expect(cssRule('.item-card::before')).toContain('padding: var(--quality-frame-width)')
    expect(cssRule('.item-card::before')).toContain('mask-composite: exclude')
    expect(cssRule('.item-card::after')).toContain('inset: 0')
    expect(cssRule('.item-card::after')).toContain('background-size')
    expect(cssRule('.item-card::after')).toContain('background-position')
    expect(cssRule('.item-card::after')).not.toContain('transform')
    expect(cssRule('.item-card::after')).toContain('animation: qualityBorderShimmer')
    expect(cssRule('.item-card.quality-gold')).toContain('--quality-frame-width: 3px')
    expect(cssRule('.item-card.quality-gold')).toContain('--quality-frame-material')
    expect(cssRule('.item-card.quality-diamond')).toContain('--quality-frame-width: 3px')
    expect(cssRule('.item-card.quality-diamond')).toContain('--quality-frame-material')
    expect(css).not.toMatch(/\.item-card\.quality-gold,\s*\.shop-card\.quality-gold,\s*\.tip-tag\.quality-gold\s*\{[^}]*border-width:\s*5px/s)
    expect(css).not.toMatch(/\.item-card\.quality-diamond,\s*\.shop-card\.quality-diamond,\s*\.tip-tag\.quality-diamond\s*\{[^}]*border-width:\s*5px/s)
    expect(cssRule('.item-card.quality-gold::after, .item-card.quality-diamond::after')).toContain('opacity')
    expect(cssRule('.item-card.quality-bronze::after, .item-card.quality-silver::after')).toContain('animation: none')
    expect(css).toContain('@keyframes qualityBorderShimmer')
    expect(cssRule('@keyframes qualityBorderShimmer')).toContain('background-position')
    expect(cssRule('@keyframes qualityBorderShimmer')).not.toContain('transform')
    expect(cssRule('@media (prefers-reduced-motion: reduce)')).toContain('.item-card::after')
  })

  it('adds tone-driven item card art windows with readable text bands', () => {
    for (const tone of ['damage', 'poison', 'shield', 'heal', 'weak', 'freeze', 'thorns', 'economy', 'growth', 'counter', 'trigger', 'utility']) {
      expect(cssRule(`.item-tone-${tone}`)).toContain('--item-tone-main')
      expect(cssRule(`.item-tone-${tone}`)).toContain('--item-tone-soft')
      expect(cssRule(`.item-tone-${tone}`)).toContain('--item-tone-ink')
      expect(cssRule(`.item-tone-${tone}`)).toContain('--item-art-glow')
    }
    expect(cssRule('.item-tone-heal')).toContain('--item-tone-main: #86efac')
    expect(cssRule('.item-tone-heal')).toContain('--item-tone-soft: #ecfdf5')
    expect(cssRule('.item-tone-poison')).toContain('--item-tone-main: #166534')
    expect(cssRule('.item-tone-poison')).toContain('--item-tone-ink: #052e16')

    expect(cssRule('.item-card')).toContain('background: var(--paper-grain)')
    expect(cssRule('.item-art-window')).toContain('aspect-ratio')
    expect(cssRule('.item-art-window')).toContain('background')
    expect(cssRule('.item-art-window.icon-art::before')).toContain('var(--item-tone-main)')
    expect(cssRule('.item-card-icon-art')).toContain('object-fit: contain')
    expect(cssRule('.item-card-icon-art')).toContain('width: min(74%, 78px)')
    expect(cssRule('.shop-card-art .item-card-icon-art')).toContain('width: 40px')
    expect(cssRule('.tip-art-preview .item-card-icon-art')).toContain('width: 74px')
    expect(cssRule('.item-card-copy')).toContain('background')
    expect(cssRule('.size-badge[class*="item-tone-"]')).toContain('var(--item-tone-soft)')
    expect(cssRule('.tip-icon-frame[class*="item-tone-"]')).toContain('var(--item-tone-soft)')
    expect(cssRule('.battle-item .item-art-window')).toContain('min-height')
    expect(cssRule('.shop-card-art')).toContain('background')
    expect(cssRule('.tip-art-preview')).toContain('background')
    expect(cssRule('.item-art-debug-gallery')).toContain('min-height')
    expect(cssRule('.item-art-debug-grid')).toContain('repeat(auto-fill')
    expect(cssRule('.item-art-debug-card')).toContain('grid-template-columns')
  })

  it('turns equipment and bag grids into wooden handdrawn trays', () => {
    expect(cssRule(':root')).toContain('--wood-frame')
    expect(cssRule(':root')).toContain('--wood-grain')
    expect(cssRule(':root')).toContain('--wood-shadow')
    expect(cssRule('.paper-inventory .slot-grid')).toContain('var(--wood-frame)')
    expect(cssRule('.paper-inventory .slot-grid')).toContain('var(--wood-grain)')
    expect(cssRule('.paper-inventory .slot-grid')).toContain('var(--wood-shadow)')
    expect(cssRule('.paper-inventory .slot-grid::after')).toContain('var(--rough-ink-edge)')
    expect(cssVariableValue('--wood-grain')).toContain('repeating-linear-gradient(87deg')
    expect(cssRule('.paper-inventory .slot')).toContain('inset 0 0 0 2px rgba(92, 54, 27, .2)')
    expect(cssRule('.paper-inventory .slot')).toContain('linear-gradient(180deg, #efd1a3, #d2a066)')
    expect(cssRule('.battle-slot-grid')).toContain('var(--wood-frame)')
    expect(cssRule('.battle-slot-grid')).toContain('var(--wood-grain)')
    expect(cssRule('.battle-slot')).toContain('inset 0 0 0 2px rgba(92, 54, 27, .2)')
  })

  it('adds rough layered paper edges so panels feel less mechanically rectangular', () => {
    expect(cssRule(':root')).toContain('--rough-ink-edge')
    expect(cssRule(':root')).toContain('--lifted-paper-shadow')
    expect(cssRule('.paper-card::before')).toContain('var(--rough-ink-edge)')
    expect(cssRule('.paper-card::before')).toContain('clip-path')
    expect(cssRule('.paper-card::after')).toContain('box-shadow: var(--lifted-paper-shadow)')
    expect(cssRule('.dog-card, .choice, .shop-shelf, .inventory-board, .match-panel, .battle-panel')).toContain('box-shadow: var(--lifted-paper-shadow)')
    expect(cssRule('.sketch-panel')).toContain('box-shadow: var(--lifted-paper-shadow)')
    expect(cssRule('.shop-shelf::after, .inventory-board::after, .battle-stage::after, .reward-panel::after')).toContain('var(--rough-ink-edge)')
  })

  it('adds layered bevel detail to HUD controls, buttons, and tray slots', () => {
    expect(cssRule(':root')).toContain('--control-bevel')
    expect(cssRule(':root')).toContain('--control-top-gloss')
    expect(cssRule(':root')).toContain('--slot-cavity-shadow')
    expect(cssRule('.topbar::before')).toContain('var(--control-top-gloss)')
    expect(cssRule('.resource-pill::before, .dog-trait-summary::before')).toContain('var(--control-bevel)')
    expect(cssRule('.icon-button::before, .action-button::before, .primary::before, .secondary::before, .danger-button::before, .reroll-button::before, .log-toggle::before, .speed-row button::before')).toContain('var(--control-top-gloss)')
    expect(cssRule('.speed-row')).toContain('var(--control-bevel)')
    expect(cssRule('.paper-inventory .slot::before, .battle-slot::before')).toContain('var(--slot-cavity-shadow)')
    expect(cssRule('.paper-inventory .slot::after, .battle-slot::after')).toContain('linear-gradient(135deg, rgba(255, 255, 255, .3), transparent')
    expect(cssRule('.battle-slot-grid::before, .paper-inventory .slot-grid::before')).toContain('var(--wood-grain)')
  })
})
