import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const css = readFileSync(new URL('./App.css', import.meta.url), 'utf8')
const data = readFileSync(new URL('./server/game/data.ts', import.meta.url), 'utf8')

function mappedAssetIds(recordName: string) {
  const start = app.indexOf(`const ${recordName}: Record<string, string> = {`)
  const end = app.indexOf('\n}', start)
  const record = app.slice(start, end)
  return [...record.matchAll(/['`]([^'`]+)['`]:\s*['`]([^'`]+)['`]/g)].map(([, id, path]) => ({ id, path }))
}

function itemDefIds() {
  const slotIds = [...data.matchAll(/slotItem\(\s*['`]([^'`]+)['`]/g)]
    .map((match) => match[1])
    .filter((id) => id !== 'starter-${n}')
  const classIds = [...data.matchAll(/classItem\(\s*['`][^'`]+['`]\s*,\s*\d+\s*,\s*['`]([^'`]+)['`]/g)]
    .map((match) => match[1])
  return [...new Set(['starter-1', 'starter-2', 'starter-3', 'starter-4', 'starter-5', 'starter-6', ...slotIds, ...classIds])]
}

function relicDefIds() {
  const relicBlock = data.slice(data.indexOf('export const RELIC_DEFS'), data.indexOf('export const ALL_ITEM_DEFS'))
  return [...relicBlock.matchAll(/\{\s*id:\s*['`]([^'`]+)['`]/g)].map((match) => match[1])
}

describe('selection screen structure', () => {
  it('renders a mode lobby and opens the peak arena screen from the peak card', () => {
    expect(app).toContain("type GameMode = 'CASUAL' | 'LADDER' | 'DOGFIGHT' | 'PEAK'")
    expect(app).toContain("type AppScreen = 'LOBBY' | 'CASUAL' | 'LADDER' | 'DOGFIGHT' | 'PEAK'")
    expect(app).toContain("const [appScreen, setAppScreen] = useState<AppScreen>('LOBBY')")
    expect(app).toContain('function ModeLobby')
    expect(app).toContain('休闲模式')
    expect(app).toContain('天梯模式')
    expect(app).toContain('斗狗模式')
    expect(app).toContain('巅峰模式')
    expect(app).toContain('战斗结束后的狗进入巅峰竞技场')
    expect(app).toContain('onEnterPeak={() => setAppScreen(\'PEAK\')}')
    expect(app).toContain('进入巅峰模式')
  })

  it('unlocks ladder mode with profile, leaderboard, and settlement formula hooks', () => {
    expect(app).toContain('function LadderHome')
    expect(app).toContain("api<LadderMeResponse>('/ladder/me')")
    expect(app).toContain("api<LadderLeaderboardResponse>('/ladder/leaderboard')")
    expect(app).toContain("onEnterLadder={() => setAppScreen('LADDER')}")
    expect(app).toContain("body: JSON.stringify({ ...choice, mode: 'LADDER' })")
    expect(app).toContain('犬王积分榜')
    expect(app).toContain('ladderSettlement')
    expect(app).toContain('基础 {settlement.baseScore >= 0 ?')
  })

  it('wires dogfight mode to room APIs and shows room actions plus spectator entry points', () => {
    expect(app).toContain('function DogfightLobby')
    expect(app).toContain('function DogfightRoomView')
    expect(app).toContain("api<DogfightRoomsResponse>('/dogfight/rooms')")
    expect(app).toContain("api<DogfightRoomResponse>('/dogfight/rooms'")
    expect(app).toContain("api<DogfightRoomResponse>('/dogfight/match'")
    expect(app).toContain("api<DogfightRoomResponse>(`/dogfight/rooms/${roomId}/join`")
    expect(app).toContain("api<DogfightLeaveResponse>(`/dogfight/rooms/${room.id}/leave`")
    expect(app).toContain("api<DogfightRoomResponse>(`/dogfight/rooms/${room.id}/ready`")
    expect(app).toContain("api<DogfightRoomResponse>(`/dogfight/rooms/${room.id}/dog-choice`")
    expect(app).toContain("api<DogfightBattleResponse>(`/dogfight/battles/${battleId}`")
    expect(app).toContain("onEnterDogfight={() => setAppScreen('DOGFIGHT')}")
    expect(app).toContain("phase: DogfightRoomPhase")
    expect(app).toContain("phaseDeadline: string | null")
    expect(app).toContain("targetPlayerCount: number")
    expect(app).toContain("kind: 'PLAYER' | 'BOT'")
    expect(app).toContain('currentBattleId?: string | null')
    expect(app).toContain('currentRunMember: DogfightMember | null')
    expect(app).toContain('function dogfightPhaseLabel')
    expect(app).toContain('function sortedDogfightMembers')
    expect(app).toContain('return rightLives - leftLives')
    expect(app).toContain('DOG_SELECT')
    expect(app).toContain('SHOP')
    expect(app).toContain('BATTLE')
    expect(app).toContain('dogfight-run-stats')
    expect(app).toContain('创建房间')
    expect(app).toContain('加入房间')
    expect(app).toContain('随机匹配')
    expect(app).toContain('房间列表')
    expect(app).toContain("room.status === 'WAITING' ? '加入房间' : '观战'")
    expect(app).toContain('剩余存活')
    expect(app).toContain('玩家席位')
    expect(app).toContain('机器人')
    expect(app).toContain('选择斗狗')
    expect(app).toContain('完成本回合')
    expect(app).toContain('本轮场次')
    expect(app).not.toContain('斗狗胜场上限')
    expect(css).toContain('.dogfight-screen')
    expect(css).toContain('.dogfight-layout')
    expect(css).toContain('.dogfight-room-list')
    expect(css).toContain('.dogfight-survivor-board')
    expect(css).toContain('.dogfight-player-frame')
    expect(css).toContain('.dogfight-phase-track')
    expect(css).toContain('.dogfight-run-stats')
  })

  it('shows five-loss tolerance for casual runs in the top banner', () => {
    expect(app).toContain('value={`${5 - run.losses}`}')
    expect(app).toContain("tone={5 - run.losses <= 1 ? 'danger' : 'safe'}")
    expect(app).not.toContain('value={`${3 - run.losses}`}')
    expect(app).not.toContain("tone={3 - run.losses <= 1 ? 'danger' : 'safe'}")
  })

  it('keeps the current dog trait visible in the top banner during a run', () => {
    expect(app).toContain('<DogTraitSummary run={run} />')
    expect(app).toContain('function DogTraitSummary')
    expect(app).toContain('dogTraits[run.dogType]')
    expect(app).toContain('run.dogType === \'EMPEROR\' && run.luckyNumber')
    expect(css).toContain('.dog-trait-summary')
    expect(css).toContain('.dog-trait-summary img')
    expect(css).toContain('.dog-trait-summary p')
  })

  it('wires peak arena to apex APIs and keeps the lobby button in the top banner', () => {
    expect(app).toContain('function ApexArena')
    expect(app).toContain("api<ApexOverview>('/apex')")
    expect(app).toContain("api<ApexSubmitResponse>('/apex/submit'")
    expect(app).toContain('可投入的完成狗')
    expect(app).toContain('先在休闲模式完成一局，再回来冲榜。')
    expect(app).toContain('leaderboards: result.leaderboards')
    expect(app).toContain('总榜')
    expect(app).toContain('当日榜')
    expect(app).toContain('每日 05:00 更新')
    expect(app).toContain('candidates: current?.candidates.filter((run) => run.id !== runId) ?? []')
    expect(app).toContain('expandedEntryId')
    expect(app).toContain('function ApexSnapshotDetails')
    expect(app).toContain('const [inspectedItem, setInspectedItem] = useState<Item | null>(null)')
    expect(app).toContain('onClick={(event) => setInspectedItemWithAnchor(item, event.currentTarget)}')
    expect(app).toContain('<FloatingTip run={apexTipRun} item={inspectedItem} offer={null} anchor={tipAnchor} onClose={closeTip} onBuy={null} onSell={null} onUpgrade={null} />')
    expect(app).toContain('查看配置')
    expect(app).toContain('收起配置')
    expect(app).toContain('<RelicRail relics={entry.relics} />')
    expect(app).toContain('title="模式大厅"')
    expect(app).toContain('aria-label="模式大厅"')
    expect(app).toContain('setAppScreen(\'LOBBY\')')
    expect(css).toContain('.apex-screen')
    expect(css).toContain('.apex-layout')
    expect(css).toContain('.apex-rank-row.player-entry')
  })

  it('adds responsive mode lobby styling hooks', () => {
    expect(css).toContain('.mode-lobby-screen')
    expect(css).toContain('.mode-grid')
    expect(css).toContain('.mode-card.locked')
    expect(css).toContain('.lock-chain')
    expect(css).toContain('grid-template-columns: repeat(2, minmax(260px, 1fr))')
    expect(css).toContain('grid-template-columns: 1fr')
  })

  it('keeps dog selection as an eight-slot gallery with a detail panel', () => {
    expect(app).toContain('DOG_SELECTION_SLOT_COUNT = 8')
    expect(app).toContain('dog-card placeholder')
    expect(app).toContain('dog-detail-panel')
    expect(app).toContain('开始一局')
    expect(css).toContain('grid-template-columns: minmax(0, 1fr) 360px')
    expect(css).toContain('grid-template-columns: repeat(4, minmax(140px, 1fr))')
    expect(css).toContain('.dog-detail-art .dog-avatar.large')
    expect(css).toContain('width: 86%')
  })

  it('offers dog emperor with a lucky-number selector and picture avatars', () => {
    expect(app).toContain("type DogType = 'SHIBA' | 'SAMOYED' | 'MUTT' | 'BULLY' | 'EMPEROR'")
    expect(app).toContain("EMPEROR: '狗皇帝'")
    expect(app).toContain("EMPEROR: '/assets/dogs/emperor.webp'")
    expect(app).toContain('luckyNumber')
    expect(app).toContain('幸运数字')
    expect(app).toContain("SHIBA: '/assets/dogs/shiba.webp'")
    expect(app).toContain("SAMOYED: '/assets/dogs/samoyed.webp'")
    expect(app).toContain("MUTT: '/assets/dogs/mutt.webp'")
    expect(app).toContain("BULLY: '/assets/dogs/bully.webp'")
  })

  it('keeps shop choices in a seven-slot board and pads missing choices with blanks', () => {
    expect(app).toContain('SHOP_CHOICE_SLOT_COUNT = 7')
    expect(app).toContain('choice placeholder')
    expect(app).toContain('ShopChoiceSelect')
    expect(app).toContain("进入 {selectedChoice ? shopNames[selectedChoice] : '商店'}")
    expect(css).toContain('grid-template-columns: repeat(3, minmax(240px, 1fr))')
    expect(css).toContain('.choice.placeholder')
  })

  it('does not render the removed chapter progress or page navigator', () => {
    expect(app).not.toContain('<ChapterProgress')
    expect(app).not.toContain('<PageNav')
    expect(app).not.toContain('function ChapterProgress')
    expect(app).not.toContain('function PageNav')
  })

  it('does not render the player account under the top title', () => {
    expect(app).not.toContain('<p>{user}</p>')
    expect(app).not.toContain('function TopBar({ user')
    expect(app).not.toContain('user: string; run?: Run')
  })

  it('uses the same compact top banner on setup and gameplay screens', () => {
    expect(app).toContain('<main className="app-shell">')
    expect(app).not.toContain('entry-shell')
    expect(app).not.toContain('const shellClass')
    expect(css).not.toContain('.entry-shell')
    expect(css).toContain('height: 58px')
    expect(css).toContain('margin: 12px auto 0')
    expect(css).toContain('align-content: start')
    expect(css).toContain('grid-template-rows: auto auto')
    expect(css).toContain('align-self: start')
    expect(css).toContain('justify-items: center')
    expect(css).toContain('width: 42px')
  })

  it('uses the same compact banner and rectangular action rhythm on gameplay screens', () => {
    expect(app).toContain('<main className="app-shell">')
    expect(app).not.toContain('entry-shell')
    expect(app).toContain('window.scrollTo(0, 0)')
    expect(app).toContain('run?.phase')
    expect(app.indexOf('className="battle-continue-row"')).toBeGreaterThan(-1)
    expect(app.indexOf('className="battle-continue-row"')).toBeLessThan(app.indexOf('<CollapsedBattleLog'))
    expect(css).toContain('height: 58px')
    expect(css).toContain('min-height: 150px')
    expect(css).toContain('width: min(184px, 100%)')
    expect(css).toContain('justify-self: center')
    expect(css).toContain('.battle-continue-row')
  })

  it('defers battle result data updates until playback is continued', () => {
    expect(app).toContain("run.phase === 'BATTLE'")
    expect(app).toContain('/battle/finish')
    expect(app).toContain("run.phase === 'BATTLE' && isFinished")
  })

  it('does not automatically reopen a dismissed dogfight battle replay', () => {
    expect(app).toContain('dismissedAutoBattleId')
    expect(app).toContain('if (dismissedAutoBattleId === battleId) return')
    expect(app).toContain('finishDogfightBattleReplay')
    expect(app).toContain("onContinue={() => finishDogfightBattleReplay()}")
  })

  it('offers active runs a confirmed forfeit settlement action outside battle playback', () => {
    expect(app).toContain('function ForfeitRunAction')
    expect(app).toContain('window.confirm')
    expect(app).toContain('/settle')
    expect(app).toContain("run.status === 'ACTIVE'")
    expect(app).toContain("run.phase !== 'BATTLE'")
    expect(app).toContain("{!battle && !showClassRewardCeremony && run.status === 'ACTIVE' && run.phase !== 'BATTLE' && (")
    expect(app).toContain('onForfeit={() => void settleRun()}')
    expect(css).toContain('.forfeit-run-action')
  })

  it('does not show the previous battle snapshot outside playback', () => {
    expect(app).not.toContain('function LastBattleRecord')
    expect(app).not.toContain('<LastBattleRecord run={run} />')
    expect(app).not.toContain('className="last-battle-record"')
    expect(css).not.toContain('.last-battle-record')
  })

  it('shows player run history in the mode lobby as the multi-game battle record', () => {
    expect(app).toContain('type PlayerRunHistory')
    expect(app).toContain('const [ladderProfile, setLadderProfile]')
    expect(app).toContain('const [runHistory, setRunHistory]')
    expect(app).toContain('const [historyOverlayOpen, setHistoryOverlayOpen]')
    expect(app).toContain('type HistoryModeTab')
    expect(app).toContain("api<{ history: PlayerRunHistory }>('/runs/history')")
    expect(app).toContain('function PlayerRunHistoryPanel')
    expect(app).toContain('function PlayerHistoryOverlay')
    expect(app).toContain('<PlayerRunHistoryPanel history={runHistory} ladderProfile={ladderProfile} onOpen={() => setHistoryOverlayOpen(true)} />')
    expect(app).toContain('<ModeLobby run={run}')
    expect(app).toContain('<PlayerHistoryOverlay history={runHistory} onClose={() => setHistoryOverlayOpen(false)} />')
    expect(app).toContain('个人战绩')
    expect(app).toContain('天梯段位')
    expect(app).toContain('犬爪奖杯')
    expect(app).toContain('history-ladder-slot')
    expect(app).toContain('最近对局')
    expect(app).toContain('全部')
    expect(app).toContain('休闲模式')
    expect(app).toContain('斗狗模式')
    expect(app).toContain('巅峰模式')
    expect(app).toContain('天梯模式')
    expect(app).toContain('休闲或天梯完成后的狗可以送入巅峰竞技场')
    expect(app).toContain('查看装备')
    expect(css).toContain('.player-history-panel')
    expect(css).toContain('.history-ladder-slot')
    expect(css).toContain('.dog-rank-trophy')
    expect(css).toContain('.player-history-overlay')
    expect(css).toContain('.history-mode-tabs')
    expect(css).toContain('.history-run-list')
  })

  it('limits the mode lobby history strip to the latest five runs', () => {
    expect(app).toContain('const lobbyRecentRuns = history.recentRuns.slice(0, 5)')
    expect(app).toContain('lobbyRecentRuns.length > 0 ? lobbyRecentRuns.map((entry) => (')
  })

  it('renders battle health bars as a percentage of max health', () => {
    expect(app).toContain('playerMaxHp')
    expect(app).toContain('opponentMaxHp')
    expect(app).toContain('const hpPercent = maxHp > 0 ? (hp / maxHp) * 100 : 0')
  })

  it('renders battle shield bars from playback event shield values', () => {
    expect(app).toContain('playerShield')
    expect(app).toContain('opponentShield')
    expect(app).toContain('shield={opponentShield}')
    expect(app).toContain('shield={playerShield}')
    expect(app).toContain('className="shield-bar"')
    expect(css).toContain('.shield-bar')
  })

  it('renders positive statuses above health and negative statuses below with poison preview damage', () => {
    expect(app).toContain('function StatusEffectRow')
    expect(app).toContain('positiveStatuses')
    expect(app).toContain('negativeStatuses')
    expect(app).toContain('poisonPreviewPercent')
    expect(css).toContain('.status-effects.positive')
    expect(css).toContain('.status-effects.negative')
    expect(css).toContain('.hp-preview.poison')
  })

  it('shows exact current values in battle status chips and tooltips', () => {
    expect(app).toContain('STATUS_THORNS_DAMAGE_PER_STACK = 2')
    expect(app).toContain('反伤${stacks * STATUS_THORNS_DAMAGE_PER_STACK}')
    expect(app).toContain('每秒${poisonTickDamage(status)}伤')
    expect(app).toContain('下次伤害-50%')
    expect(app).toContain('伤害+${stacks * STATUS_FURY_DAMAGE_PER_STACK}')
    expect(app).toContain('间隔-${formatStatusSeconds(stacks * STATUS_SPEED_REDUCTION_PER_STACK)}s')
    expect(app).toContain('title={statusDescription(status)}')
  })

  it('highlights poison battle effects with green damage and log styling', () => {
    expect(app).toContain("poison: { kind: 'poison', color: '#22c55e'")
    expect(css).toContain('.battle-log p.poison')
  })

  it('shows item effects directly on equipment cards', () => {
    expect(app).toContain('className="item-effect"')
    expect(app).toContain('effectText(item.def, normalizeQuality(item.quality))')
    expect(css).toContain('.item-effect')
  })

  it('hides full-range trigger dice on direct-trigger item surfaces', () => {
    expect(app).toContain("import { triggerDiceLabel } from './item-trigger-display'")
    expect(app).toContain('const triggerDice = triggerDiceLabel(item.def)')
    expect(app).toContain('{triggerDice && <small><Dice5 size={12} /> {triggerDice}</small>}')
    expect(app).toContain('const tipTriggerDice = triggerDiceLabel(def)')
    expect(app).toContain('{tipTriggerDice && (')
    expect(app).not.toContain('<small><Dice5 size={12} /> {item.def.dice.join')
  })

  it('renders class reward, relic slots, and rule term tooltip surfaces', () => {
    expect(app).toContain('ClassRewardCeremony')
    expect(app).toContain('ClassRewardSelect')
    expect(app).toContain('RelicChoiceSelect')
    expect(app).toContain('RelicRail')
    expect(app).toContain('RuleText')
    expect(app).toContain('rule-term')
    expect(app).toContain('rule-tip')
    expect(app).toContain("import { TERM_DEFS } from './shared/rule-terms'")
    expect(app).toContain('Object.fromEntries(TERM_DEFS.map')
    expect(data).toContain("import { TERM_DEFS } from '../../shared/rule-terms'")
    expect(data).toContain('export { TERM_DEFS }')
    expect(data).not.toContain('export const TERM_DEFS = [')
  })

  it('maps every item and relic definition to a dedicated SVG icon asset', () => {
    const itemIconEntries = mappedAssetIds('itemIcons')
    const relicIconEntries = mappedAssetIds('relicIcons')
    const itemIconIds = itemIconEntries.map((entry) => entry.id)
    const relicIconIds = relicIconEntries.map((entry) => entry.id)

    expect(itemDefIds().filter((id) => !itemIconIds.includes(id))).toEqual([])
    expect(relicDefIds().filter((id) => !relicIconIds.includes(id))).toEqual([])
    expect(itemIconEntries.filter((entry) => !existsSync(new URL(`../public${entry.path}`, import.meta.url)))).toEqual([])
    expect(relicIconEntries.filter((entry) => !existsSync(new URL(`../public${entry.path}`, import.meta.url)))).toEqual([])
  })

  it('places the relic rail to the left of the bag grid', () => {
    const rowStart = app.indexOf('className="bag-relic-row"')
    const rowEnd = app.indexOf('</div>', rowStart)
    const rowMarkup = app.slice(rowStart, rowEnd)

    expect(rowMarkup.indexOf('<RelicRail')).toBeGreaterThan(-1)
    expect(rowMarkup.indexOf('area="BAG"')).toBeGreaterThan(-1)
    expect(rowMarkup.indexOf('<RelicRail')).toBeLessThan(rowMarkup.indexOf('area="BAG"'))
  })

  it('keeps relic rail slots icon-only and moves details into a click tip', () => {
    expect(app).toContain('const [selectedRelicId, setSelectedRelicId] = useState<string | null>(null)')
    expect(app).toContain('className="relic-icon-button"')
    expect(app).toContain('function RelicGlyph')
    expect(app).toContain('<RelicGlyph relic={relic} size={30} />')
    expect(app).toContain('<RelicGlyph relic={relic} size={44} />')
    expect(app).toContain('<RelicFloatingTip')
    expect(app).toContain('relic-floating-tip floating-tip')
    expect(app).toContain('setSelectedRelicId(selectedRelicId === relic.id ? null : relic.id)')

    const relicRailStart = app.indexOf('function RelicRail')
    const relicRailEnd = app.indexOf('function GridPanel', relicRailStart)
    const relicRailMarkup = app.slice(relicRailStart, relicRailEnd)

    expect(relicRailMarkup).not.toContain('<strong>{relic.def.name}</strong>')
    expect(relicRailMarkup).not.toContain('<small><RuleText text={relic.def.description} /></small>')
  })

  it('lets inspected backpack relics be sold for zero gold', () => {
    expect(app).toContain('onSellRelic')
    expect(app).toContain('/relic/sell')
    expect(app).toContain('body: JSON.stringify({ relicId })')
    expect(app).toContain('出售 +0')
  })

  it('gates class reward selection behind a dismissible awakening ceremony', () => {
    expect(app).toContain('classRewardCeremonyKey')
    expect(app).toContain('ceremonyDismissedRounds')
    expect(app).toContain('!ceremonyDismissedRounds.has(classRewardCeremonyKey)')
    expect(app).toContain('onDismiss={() => dismissClassRewardCeremony(classRewardCeremonyKey)}')
    expect(app).toContain('run.phase === \'CLASS_REWARD\' && showClassRewardCeremony')
    expect(app).toContain('run.phase === \'CLASS_REWARD\' && !showClassRewardCeremony')
  })

  it('lets players skip the class reward ceremony with click, Enter, or Space', () => {
    expect(app).toContain('function handleCeremonyKeyDown')
    expect(app).toContain("event.key === 'Enter' || event.key === ' '")
    expect(app).toContain('onClick={onDismiss}')
    expect(app).toContain('onKeyDown={handleCeremonyKeyDown}')
    expect(app).toContain('role="button"')
    expect(app).toContain('tabIndex={0}')
  })

  it('keeps rule tooltip buttons out of nested choice buttons', () => {
    expect(app).toContain('function handleChoiceCardKeyDown')
    expect(app).toContain('<div key={choice.defId} role="button"')
    expect(app).toContain('<div key={choice.relicId} role="button"')
    expect(app).not.toContain('<button key={choice.defId} className={`choice reward-choice')
    expect(app).not.toContain('<button key={choice.relicId} className={`choice relic-choice')
  })

  it('anchors dog card tags at the bottom for a consistent gallery rhythm', () => {
    expect(css).toContain('.dog-card .tag-row')
    expect(css).toContain('margin-top: auto')
    expect(css).toContain('align-self: end')
    expect(css).toContain('grid-template-rows: auto auto minmax(0, 1fr) auto')
  })

  it('uses stable rows on shop choice cards to avoid similar floating content', () => {
    expect(css).toContain('grid-template-rows: auto auto minmax(0, 1fr)')
    expect(css).toContain('.choice > span:last-of-type')
    expect(css).toContain('align-self: stretch')
  })

  it('gates newly registered players behind nickname setup', () => {
    expect(app).toContain('needsNickname')
    expect(app).toContain('NicknameSetup')
    expect(app).toContain('/profile/nickname')
  })

  it('uses account and password auth controls with balanced login buttons', () => {
    expect(app).toContain('type AuthUser = { id: string; account: string; nickname: string | null }')
    expect(app).toContain('function createDefaultAccount')
    expect(app).toContain('const [account, setAccount]')
    expect(app).toContain('JSON.stringify({ account, password })')
    expect(app).toContain('<label>账号<input')
    expect(app).not.toContain('<label>邮箱<input')
    expect(css).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(css).toContain('.auth-panel .row .action-button')
    expect(css).toContain('width: 100%')
  })

  it('wires default-on background music through the logged-in shell', () => {
    expect(app).toContain("backgroundMusicSrc = '/assets/audio/the-final-inventory.mp3'")
    expect(app).toContain("musicPreferenceKey = 'dogfight:background-music'")
    expect(app).toContain("localStorage.getItem(musicPreferenceKey) !== 'off'")
    expect(app).toContain('document.addEventListener(\'visibilitychange\', syncPageAudioFocus)')
    expect(app).toContain("window.addEventListener('focus', syncPageAudioFocus)")
    expect(app).toContain("window.addEventListener('blur', syncPageAudioFocus)")
    expect(app).toContain('const appHasAudioFocus = !document.hidden && document.hasFocus()')
    expect(app).toContain('if (!user || !appHasAudioFocus)')
    expect(app).toContain("window.localStorage.setItem(musicPreferenceKey, nextEnabled ? 'on' : 'off')")
    expect(app).toContain('audio.play().then(() => setMusicBlocked(false)).catch(() => setMusicBlocked(true))')
    expect(app).toContain('musicEnabled={musicEnabled}')
    expect(app).toContain('onToggleMusic={toggleMusic}')
    expect(app).toContain('function TopBar({ run, musicEnabled, musicBlocked, onToggleMusic, onOpenLobby, onLogout }')
    expect(app).toContain('<Music size={18} />')
    expect(app).toContain('<VolumeX size={18} />')
    expect(css).toContain('.topbar-actions')
  })

  it('wires feedback sounds into UI toast and battle playback paths', () => {
    expect(app).toContain("from './sound-feedback'")
    expect(app).toContain('soundCueForUiFeedback(kind)')
    expect(app).toContain('soundCueForBattlePresentation(presentation.kind)')
    expect(app).toContain('playFeedbackSound')
    expect(app).toContain('soundEnabled={musicEnabled}')
    expect(app).toContain('function BattleView({ run, battle, currentEvent, eventIndex, speed, score, soundEnabled, onSpeed, onContinue, onRestart }')
    expect(app).toContain('<DogfightLobby soundEnabled={musicEnabled} />')
    expect(app).toContain('<DogfightRoomView room={room} onRoomChange={setRoom} onLeave={() => void leaveRoom()} soundEnabled={soundEnabled} />')
  })

  it('exposes stable hooks for the handdrawn polish pass', () => {
    expect(app).toContain('auth-panel paper-card sticker-card')
    expect(app).toContain('topbar paper-card')
    expect(app).toContain('mode-card paper-card sticker-card')
    expect(app).toContain('dog-card paper-card paper-dog-card')
    expect(app).toContain('dog-detail-panel paper-card')
    expect(app).toContain('choice paper-card sticker-card')
    expect(app).toContain('reward-panel paper-card')
    expect(app).toContain('shop-shelf sketch-panel')
    expect(app).toContain('inventory-board expanded paper-inventory')
    expect(app).toContain('shop-card paper-shop-card')
    expect(app).toContain('floating-tip paper-card')
    expect(app).toContain('battle-panel visual-battle sketch-panel')
    expect(app).toContain('battle-equipment-row ${owner} sketch-panel')
    expect(app).toContain('battle-stage handdrawn-stage')
    expect(app).toContain('battle-fx-canvas handdrawn-fx-canvas')
    expect(app).toContain('battle-item item-card paper-item-card')
    expect(app).toContain('battle-dice handdrawn-dice')
    expect(app).toContain('result handdrawn-result paper-card')
    expect(app).toContain('status-chip handdrawn-status-chip')
    expect(app).toContain('rule-tip paper-card')
    expect(app).toContain('status-shield')
    expect(app).toContain('status-poison')
  })

  it('marks shop offers that match equipment the player already owns', () => {
    expect(app).toContain('function shopOfferOwnedCount')
    expect(app).toContain('ownedCount={shopOfferOwnedCount(run, offer)}')
    expect(app).toContain('shop-card-owned')
    expect(app).toContain('owned-badge')
  })

  it('exposes stable hooks for the battle vfx causality pass', () => {
    expect(app).toContain("from './feedback'")
    expect(app).toContain('createBattlePresentation')
    expect(app).toContain('function BattleFxStage')
    expect(app).toContain('presentation={presentation}')
    expect(app).toContain('activePresentationKind')
    expect(app).toContain('uiFeedbacks')
    expect(app).toContain('pushUiFeedback')
    expect(app).toContain('feedback-layer')
    expect(app).toContain('function battleVfxKind')
    expect(app).toContain('function battleVfxTargetSide')
    expect(app).toContain('battle-item-trigger')
    expect(app).toContain('data-vfx-kind={battleVfxKind(activeEvent)}')
    expect(app).toContain('vfx-target-${battleVfxKind(event)}')
    expect(app).toContain('createBattleFxStyle(event)')
    expect(app).toContain('drawBattleFxTrail')
    expect(app).toContain('drawHandwrittenBattleNumber')
    expect(app).toContain("kind: 'shield'")
    expect(app).toContain("kind: 'weak'")
    expect(app).toContain("kind: 'freeze'")
  })

  it('exposes boom counter accumulation hooks on battle equipment cards', () => {
    expect(app).toContain('function boomCounterStateForBattleItem')
    expect(app).toContain('boom-counter')
    expect(app).toContain('boom-counter-pop')
    expect(app).toContain('boomCounterState?.count')
    expect(app).toContain('style={{ width: `${boomCounterState.progress}%` }}')
  })
})
