import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(path, 'utf8')

describe('production deployment assets', () => {
  it('defines Docker Compose services for the app, PostgreSQL, and Caddy', () => {
    const compose = read('compose.yml')

    expect(compose).toContain('postgres:')
    expect(compose).toContain('api:')
    expect(compose).toContain('caddy:')
    expect(compose).toContain('postgres_data:')
    expect(compose).toContain('healthcheck:')
    expect(compose).toContain('wget -qO- http://127.0.0.1:4000/api/health')
  })

  it('routes HTTPS traffic and same-origin API requests through Caddy', () => {
    const caddyfile = read('Caddyfile')

    expect(caddyfile).toContain('reverse_proxy api:4000')
    expect(caddyfile).toContain('www.torcharena.online')
    expect(caddyfile).toContain('root * /srv')
    expect(caddyfile).toContain('handle /assets/*')
    expect(caddyfile).toContain('Cache-Control "public, max-age=604800"')
    expect(caddyfile).toContain('try_files {path} /index.html')
  })

  it('documents production secrets without committing real values', () => {
    const example = read('.env.example')

    expect(example).toContain('DATABASE_URL=postgresql://')
    expect(example).toContain('JWT_SECRET=')
    expect(example).toContain('TAPTAP_MINIAPP_ID=')
    expect(example).toContain('TAPTAP_MINIAPP_SECRET=')
    expect(example).toContain('TAPTAP_MINIAPP_REGION=cn')
    expect(example).toContain('DOMAIN=')
    expect(example).toContain('BACKUP_DIR=/opt/dogfight/backups')
    expect(example).toContain('LOCAL_BACKUP_RETENTION_HOURS=72')
    expect(example).toContain('OFFSITE_BACKUP_RETENTION_DAYS=30')
    expect(example).toContain('COS_BUCKET=')
    expect(example).toContain('COS_REGION=')
    expect(example).toContain('COS_SECRET_ID=')
    expect(example).toContain('COS_SECRET_KEY=')
    expect(example).toContain('ALERT_WEBHOOK_URL=')
  })

  it('uses PostgreSQL as the Prisma datasource provider', () => {
    const schema = read('prisma/schema.prisma')

    expect(schema).toContain('provider = "postgresql"')
  })

  it('copies shared server imports into the production API image', () => {
    const dockerfile = read('Dockerfile')

    expect(dockerfile).toContain('COPY src/server ./src/server')
    expect(dockerfile).toContain('COPY src/shared ./src/shared')
  })

  it('adds GitHub Actions deployment and server backup scripts', () => {
    const workflow = read('.github/workflows/deploy.yml')
    const remoteDeploy = read('deploy/remote-deploy.sh')
    const backup = read('deploy/backup-postgres.sh')
    const cron = read('deploy/install-backup-cron.sh')
    const restore = read('deploy/restore-postgres.sh')

    expect(workflow).toContain('concurrency:')
    expect(workflow).toContain('group: production-deploy')
    expect(workflow).toContain('cancel-in-progress: false')
    expect(workflow).toContain('name: Build frontend deployment marker')
    expect(workflow).toContain('EXPECTED_JS=')
    expect(workflow).toContain('EXPECTED_CSS=')
    expect(workflow).toMatch(/deploy:\s+.*?timeout-minutes: 70/s)
    expect(workflow).toContain('PRODUCTION_ENV_B64=')
    expect(workflow).toContain('PACKAGE_PATH="/tmp/dogfight-source-${{ github.sha }}.tgz"')
    expect(workflow).toContain('REMOTE_PACKAGE="/tmp/dogfight-source-${{ github.sha }}.tgz"')
    expect(workflow).toContain('REMOTE_SCRIPT="/tmp/dogfight-remote-deploy-${{ github.sha }}.sh"')
    expect(workflow).toContain('tar -czf "$PACKAGE_PATH"')
    expect(workflow).toContain('scp -i ~/.ssh/dogfight_deploy_key')
    expect(workflow).toContain('Uploading source package to Tencent Cloud')
    expect(workflow).toContain('Starting remote deploy script on Tencent Cloud')
    expect(workflow).toContain('deploy/remote-deploy.sh')
    expect(workflow).toContain('REMOTE_PACKAGE=')
    expect(workflow).toContain('REMOTE_SCRIPT=')
    expect(workflow).not.toContain('git sparse-checkout set')
    expect(workflow).not.toContain('git fetch --filter=blob:none --depth 1 origin "$GITHUB_SHA"')
    expect(workflow).toContain('-o ServerAliveInterval=15')
    expect(remoteDeploy).toContain('REMOTE_PACKAGE')
    expect(remoteDeploy).toContain('PRODUCTION_ENV_B64')
    expect(remoteDeploy).toContain('"$TEMP_DEPLOY_PATH/node_modules"')
    expect(remoteDeploy).toContain('"$TEMP_DEPLOY_PATH/dist-click"')
    expect(remoteDeploy).toContain('"$TEMP_DEPLOY_PATH/.codex-tmp"')
    expect(remoteDeploy).toContain('"$TEMP_DEPLOY_PATH/backups"')
    expect(remoteDeploy).toContain('PRODUCTION_ENV override did not include DATABASE_URL')
    expect(remoteDeploy).toContain('ENV_OVERRIDE_PATH="$TEMP_DEPLOY_PATH/.env.production.override"')
    expect(remoteDeploy).toContain('cp "$DEPLOY_PATH/.env.production" "$TEMP_DEPLOY_PATH/.env.production"')
    expect(remoteDeploy).toContain('awk -v key="$key"')
    expect(workflow).toContain('-o BatchMode=yes')
    expect(workflow).toContain('-o ConnectTimeout=20')
    expect(workflow).toContain('timeout-minutes:')
    expect(remoteDeploy).toContain('Creating predeploy PostgreSQL backup')
    expect(remoteDeploy).toContain('BACKUP_REASON=predeploy timeout 10m sh deploy/backup-postgres.sh')
    expect(remoteDeploy).toContain('Building Docker images')
    expect(workflow).toContain('bash -s')
    expect(remoteDeploy).toContain('docker compose build --no-cache api caddy')
    expect(remoteDeploy).toContain('docker compose up -d --build')
    expect(remoteDeploy).toContain('docker compose up -d --build --force-recreate --no-deps caddy')
    expect(remoteDeploy).toContain("docker compose exec -T api node --input-type=module -e")
    expect(remoteDeploy).toContain("fetch('http://127.0.0.1:4000/api/health')")
    expect(remoteDeploy).toContain("body.database !== 'ok'")
    expect(remoteDeploy).toContain('docker compose exec -T caddy cat /srv/index.html')
    expect(remoteDeploy).toContain('Caddy image does not match expected frontend assets')
    expect(remoteDeploy).toContain('https://www.torcharena.online')
    expect(remoteDeploy).toContain('Public frontend still has not switched to')
    expect(remoteDeploy).toContain('docker compose logs --tail=200 api caddy')
    expect(remoteDeploy).toContain('DATABASE_URL')
    expect(backup).toContain('pg_dump')
    expect(backup).toContain('.sql.gz')
    expect(backup).toContain('gzip -c')
    expect(backup).toContain('LOCAL_BACKUP_RETENTION_HOURS')
    expect(backup).toContain('OFFSITE_BACKUP_RETENTION_DAYS')
    expect(backup).toContain('COS_BUCKET')
    expect(backup).toContain('COS_SECRET_ID')
    expect(backup).toContain('COS_SECRET_KEY')
    expect(backup).toContain('ALERT_WEBHOOK_URL')
    expect(backup).toContain('gunzip -t')
    expect(backup).toContain('PostgreSQL database dump')
    expect(cron).toContain('17 * * * * root')
    expect(cron).toContain('23 3 * * * root')
    expect(cron).toContain('OFFSITE_BACKUP=1')
    expect(restore).toContain('RESTORE_BACKUP_FILE')
    expect(restore).toContain('gunzip -c')
    expect(restore).toContain('psql')
    expect(restore).toContain('CONFIRM_RESTORE=YES')
  })
})
